util: add unit test for Checksum
pingcap/tidb pull request #19168
Opened 2020-08-13 05:15 UTC by wshwsh12

### What problem does this PR solve?

Issue Number: TICASE-3643 checksum 1.0

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: 
Code 9 unit test case in TICASE-3643.

How it Works:

### Related changes

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

2020-08-13 05:17 UTC, wshwsh12 commented
Find one bug: When the Reader reads a block that the size is smaller than 4 bytes, it will panic but not return errChecksumFail. I fix the bug in https://github.com/pingcap/tidb/pull/19168/files#diff-7bc3f7fd86ab3dedd6a02ab521b8fc41R154.

2020-09-16 04:56 UTC, mmyj commented on util/checksum/checksum_test.go
> +	c.Assert(err, check.IsNil)
useless here?

2020-09-16 04:56 UTC, mmyj commented on util/checksum/checksum_test.go
> +func (s *testChecksumSuite) testTiCase3645(c *check.C, encrypt bool) {
testTiCase3645 -> testTiCase3646?

2020-09-16 04:56 UTC, mmyj commented on util/checksum/checksum_test.go
> +func (s *testChecksumSuite) testTiCase3646(c *check.C, encrypt bool) {
testTiCase3646 -> testTiCase3645

2020-09-16 04:56 UTC, mmyj commented on util/checksum/checksum_test.go
> +	c.Assert(err, check.IsNil)
useless here?

2020-09-16 14:57 UTC, wshwsh12 commented on util/checksum/checksum_test.go
> +func (s *testChecksumSuite) testTiCase3645(c *check.C, encrypt bool) {
My fault. I have fix it. PTAL again.

2020-09-16 14:59 UTC, wshwsh12 commented
@mmyj  All comments have been addressed. PTAL again.

2020-09-16 15:21 UTC, mmyj requested changes
almost is ok, just delete the error assert in the `writeString := "0123456789"` below.

2020-09-16 16:36 UTC, mmyj commented
LGTM

2020-09-17 03:33 UTC, XuHuaiyu commented on util/checksum/checksum_test.go
> +func (s *testChecksumSuite) testTiCase3644(c *check.C, encrypt bool) {
It'll be better to add some comment for `testTiCase36xx`, otherwise, it's hard to understand what the test does individually

2020-09-17 09:44 UTC, XuHuaiyu approved these changes
LGTM

2020-09-17 09:45 UTC, XuHuaiyu commented
/merge

2020-09-18 02:54 UTC, wshwsh12 commented
/merge

2020-09-20 08:30 UTC, zz-jason commented
/merge

2020-09-20 08:35 UTC, merged