infoschema: add digest for process list
pingcap/tidb pull request #19622
Opened 2020-08-31 10:17 UTC by lzmhhh123

### What problem does this PR solve?

Issue Number: close #19569

### What is changed and how it works?

What's Changed: add digest for processlist

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- add sql digest for process list.

2020-08-31 11:25 UTC, jackysp reviewed
LGTM

2020-08-31 11:31 UTC, SunRunAway reviewed
LGTM

2020-08-31 20:38 UTC, nullnotnil commented
It is fine to add to the processlist table in `INFORMATION_SCHEMA`, but I think `SHOW PROCESSLIST` should remain MySQL compatible. The reason being that you can not explicitly select columns from `SHOW PROCESSLIST` like you can a table, and many applications depend on column order. Even adding it to the end of the table is an issue, because it does not handle the case that MySQL may in future add additional columns.

2020-09-01 01:39 UTC, zz-jason requested changes

2020-09-01 01:39 UTC, zz-jason commented on infoschema/tables_test.go
> +			fmt.Sprintf("1 user-1 localhost information_schema Quit abc1 9223372036 %s %s", "in transaction", "do something"),
It's better not to add `digest` to the result of `SHOW PROCESSLIST`.

2020-09-02 07:34 UTC, lzmhhh123 commented
/run-all-tests

2020-09-02 08:56 UTC, lzmhhh123 commented
@zz-jason PTAL.

2020-09-05 14:55 UTC, nullnotnil commented
LGTM

2020-09-07 03:45 UTC, SunRunAway approved these changes

2020-09-07 03:45 UTC, SunRunAway commented
/merge

2020-09-07 05:23 UTC, merged