feat/agg-mem-ntile
pingcap/tidb pull request #19756
Opened 2020-09-03 07:59 UTC by Howie66

Signed-off-by: Howie <haoweili35@gmail.com>

### What problem does this PR solve?

Issue Number: close #19741 
### Release note 
- trace the memory usage of ntile AggFunc in HashAggExec

2020-09-03 07:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/tidb?pullRequest=19756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/tidb?pullRequest=19756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/tidb?pullRequest=19756) it.</sub>

2020-09-04 02:05 UTC, b41sh requested changes

2020-09-04 02:05 UTC, b41sh commented on executor/aggfuncs/builder.go
> +		return buildNtile(aggFuncDesc, ordinal)
remove this line, `buildNtile` is in `BuildWindowFunctions`

2020-09-04 02:05 UTC, b41sh commented on executor/aggfuncs/window_func_test.go
> +	finalFunc := aggfuncs.Build(s.ctx, desc, 0)
use `aggfuncs.BuildWindowFunctions` here

2020-09-04 17:12 UTC, mmyj commented on executor/aggfuncs/window_func_test.go
> +		c.Assert(err, IsNil)
I think we should check for errors first.

2020-09-05 06:46 UTC, mmyj reviewed
LGTM

2020-09-07 06:41 UTC, b41sh commented
please fix conflicting files

2020-09-08 14:53 UTC, mmyj requested changes

2020-09-08 14:53 UTC, mmyj commented on executor/aggfuncs/window_func_test.go
> +func (s *testSuite) TestMemNtile(c *C) {
we should moving this to `func_ntile_test.go`, note that don't forget to add the license.

2020-09-09 12:28 UTC, mmyj reviewed
LGTM

2020-09-09 12:29 UTC, AndreMouche commented
LGTM

2020-09-09 12:31 UTC, b41sh commented
LGTM

2020-09-09 16:04 UTC, Howie66 commented
/run-all-test

2020-09-09 16:05 UTC, Howie66 commented
/run-all-tests

2020-09-10 02:40 UTC, XuHuaiyu commented
/merge

2020-09-10 05:24 UTC, merged