try to solve tidb issue 19745
pingcap/tidb pull request #19755
Opened 2020-09-03 07:56 UTC by asiafrank

### What problem does this PR solve?

Issue Number: close #19745 

Problem Summary: Implement memDelta for varpop functions to trace the memory usage of `AggFunc`

### What is changed and how it works?

What's Changed:

Define the struct size for the following type, and implement memory track for varpop `AggFunc`

```
DefPartialResult4VarPopFloat64Size
DefPartialResult4VarPopDistinctFloat64Size
```

### Check List 

Tests 

- Unit test

### Release note 

- trace the memory usage of varpop AggFunc in `HashAggExec`

-

2020-09-03 09:37 UTC, asiafrank commented
/run-unit-test

2020-09-03 13:08 UTC, b41sh requested changes

2020-09-03 13:08 UTC, b41sh commented on executor/aggfuncs/func_varpop.go
>  		p.valSet.Insert(input)
please return `memDelta` at line 165

2020-09-04 01:16 UTC, asiafrank commented on executor/aggfuncs/func_varpop.go
>  		p.valSet.Insert(input)
Ok, I will fix this.

2020-09-04 01:51 UTC, b41sh commented
LGTM

2020-09-04 07:45 UTC, b41sh commented
/reward 600

2020-09-04 11:08 UTC, mmyj reviewed
LGTM

2020-09-04 11:46 UTC, zz-jason commented
/merge

2020-09-04 11:55 UTC, merged