statistics: reduce `HandleAutoAnalyze` memory usage
pingcap/tidb pull request #19837
Opened 2020-09-07 07:16 UTC by hidehalo

### What problem does this PR solve?

Problem Summary:

I found that `handle.(*Handle).HandleAutoAnalyze` method consumes a lot of memory during YCSB workload e, mainly due to the abuse of the following pattern:

```go
for i := 0;i < N; i++ {
    str := fmt.Sprintf("%s %s %s", "str1", "str2", "str3")  
} 
```

In this pattern, the program would allocate memory repeatedly, cost more CPU&memory. When the number of cycles N is large enough, the performance of the program may be huge hurt.

### What is changed and how it works?

What's Changed:

Replace `str := fmt.Sprintf` via `str := str1 + str2`

How it Works:

Avoid unnecessary memory allocate.

### Check List

Tests 

- Unit test
- Benchmark test

#### Bechmark before

> PASS: update_test.go:1768: testStatsSuite.BenchmarkHandleAutoAnalyze	    5000	    340482 ns/op	  164446 B/op	    2592 allocs/op

#### Benchmark after

> PASS: update_test.go:1768: testStatsSuite.BenchmarkHandleAutoAnalyze	    5000	    222281 ns/op	  113214 B/op	    1092 allocs/op

### Release note 

Reduce `HandleAutoAnalyze` memory usage

2020-09-07 07:33 UTC, lysu commented on statistics/handle/update.go
> +				sql := "analyze table `" + db + "`.`" + tblInfo.Name.O + "`" + " partition" + def.Name.O
```suggestion
				sql := "analyze table `" + db + "`.`" + tblName + "`" + " partition" + def.Name.O
```

2020-09-07 07:43 UTC, lysu requested changes

2020-09-07 07:43 UTC, lysu commented on statistics/handle/update.go
> +				sql := "analyze table `" + db + "`.`" + tblInfo.Name.O + "`" + " partition" + def.Name.O
```suggestion
				sql := "analyze table `" + db + "`.`" + tblInfo.Name.O + "`" + " partition" + "`" + def.Name.O + "`"
```
partition name also need surrounding with "`"

2020-09-07 12:23 UTC, lysu commented
/run-unit-test

2020-09-07 12:24 UTC, lysu approved these changes

2020-09-08 09:51 UTC, hidehalo commented
@eurekaka PTAL

2020-09-11 09:43 UTC, SunRunAway reviewed
LGTM

2020-09-11 09:43 UTC, SunRunAway commented
/merge

2020-09-11 13:20 UTC, hidehalo commented
/run-all-tests

2020-09-11 13:32 UTC, hidehalo commented
/merge

2020-09-11 13:33 UTC, hidehalo commented
> /merge

@SunRunAway I need you

2020-09-12 02:54 UTC, merged