Call For Participation: add memory trace for percent rank agg functions
pingcap/tidb pull request #19852
Opened 2020-09-08 02:00 UTC by Patrick0308

### What problem does this PR solve?

Issue Number: close #19742 

Problem Summary:

### What is changed and how it works?

What's Changed: 

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- add memory trace for percent rank agg functions

2020-09-08 04:35 UTC, mmyj commented on executor/aggfuncs/window_func_test.go
> +func (s *testSuite) TestMemPercentRank(c *C) {
IMO, we could move this to `func_percent_rank_test.go`. Note that don't forget the open source license for the new file.

2020-09-08 04:55 UTC, mmyj requested changes

2020-09-08 04:55 UTC, mmyj commented on executor/aggfuncs/func_percent_rank_test.go
> +// Copyright 2018 PingCAP, Inc.
2018->2020

2020-09-08 05:03 UTC, mmyj commented
LGTM

2020-09-08 05:04 UTC, mmyj commented
PTAL @b41sh

2020-09-08 07:44 UTC, b41sh commented
/reward 600

2020-09-08 07:47 UTC, b41sh commented
LGTM

2020-09-09 03:22 UTC, XuHuaiyu commented
/merge

2020-09-09 03:33 UTC, merged