executor: implement meldata for rank funcs to track memUsage
pingcap/tidb pull request #19896
Opened 2020-09-09 03:14 UTC by TszKitLo40

### What problem does this PR solve?

Problem Summary:
Nitpick for implementing memDelta for sum functions to trace the memory usage of rankFunc
### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
- move TestMemRank to func_rank_test
- bug fix in testWindowAggMemFunc

### Check List 

Tests 
- No code

### Release note 
- bugfixes

2020-09-09 03:15 UTC, TszKitLo40 commented
@mmyj @b41sh PLAT

2020-09-09 04:05 UTC, mmyj commented
Should we modify the title to descript the change of this pr.
how ablout `implement meldata for rank funcs to track memUsage` -> `fix the unit test of the rank funcs memUsage tracking`?

2020-09-09 05:04 UTC, TszKitLo40 commented
> Should we modify the title to descript the change of this pr.
> how ablout `implement meldata for rank funcs to track memUsage` -> `fix the unit test of the rank funcs memUsage tracking`?

Yes, good idea.

2020-09-09 05:10 UTC, mmyj commented on executor/aggfuncs/func_rank_test.go
> +	"github.com/pingcap/tidb/executor/aggfuncs"
Should we format it?

2020-09-09 05:10 UTC, mmyj commented
LGTM

2020-09-09 06:15 UTC, TszKitLo40 commented on executor/aggfuncs/func_rank_test.go
> +	"github.com/pingcap/tidb/executor/aggfuncs"
This file has been formatted.

2020-09-09 10:46 UTC, mmyj commented on executor/aggfuncs/func_rank_test.go
> +	"github.com/pingcap/tidb/executor/aggfuncs"
ok

2020-09-09 13:20 UTC, b41sh commented
LGTM

2020-09-10 03:37 UTC, mmyj requested changes

2020-09-10 03:37 UTC, mmyj commented on executor/aggfuncs/func_rank_test.go
> +
we need delete this empty line.

2020-09-10 03:43 UTC, TszKitLo40 commented on executor/aggfuncs/func_rank_test.go
> +
I have deleted it.

2020-09-10 04:58 UTC, mmyj commented
LGTM

2020-09-13 05:32 UTC, wshwsh12 commented
/merge

2020-09-14 02:09 UTC, TszKitLo40 commented
@wshwsh12 @mmyj @b41sh How to fix the merge failure?

2020-09-14 02:37 UTC, mmyj commented
retry once？

2020-09-14 03:57 UTC, wshwsh12 commented
/merge

2020-09-14 04:45 UTC, merged