executor: add coprocessor cache hit rate in explain analyze
pingcap/tidb pull request #19948
Opened 2020-09-11 06:32 UTC by lzmhhh123

### What problem does this PR solve?

Issue Number: close #17370

### What is changed and how it works?

How it Works: add coprocessor cache hit rate in explain analyze.

here is an example:

```sql
tidb(localhost:4001) > explain analyze select * from t use index(a);
+-------------------------------+-----------+---------+-----------+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+-----------------------+------+
| id                            | estRows   | actRows | task      | access object          | execution info                                                                                                                                                                                                                                           | operator info                  | memory                | disk |
+-------------------------------+-----------+---------+-----------+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+-----------------------+------+
| IndexLookUp_6                 | 262400.00 | 262400  | root      |                        | time:620.513742ms, loops:258, cop_task: {num: 4, max: 5.530817ms, min: 1.51829ms, avg: 2.70883ms, p95: 5.530817ms, max_proc_keys: 2480, p95_proc_keys: 2480, tot_proc: 1ms, tot_wait: 1ms, rpc_num: 4, rpc_time: 10.816328ms, copr_cache_hit_rate: 0.75} |                                | 6.685169219970703 MB  | N/A  |
| ├─IndexFullScan_4(Build)      | 262400.00 | 262400  | cop[tikv] | table:t, index:a(a, c) | proc max:93ms, min:1ms, p80:93ms, p95:93ms, iters:275, tasks:4                                                                                                                                                                                           | keep order:false, stats:pseudo | 1.7549400329589844 MB | N/A  |
| └─TableRowIDScan_5(Probe)     | 262400.00 | 0       | cop[tikv] | table:t                | time:0ns, loops:0                                                                                                                                                                                                                                        | keep order:false, stats:pseudo | N/A                   | N/A  |
+-------------------------------+-----------+---------+-----------+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+-----------------------+------+
3 rows in set (0.62 sec)
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- add coprocessor cache hit rate in explain analyze.

2020-09-11 06:39 UTC, qw4990 commented on distsql/select_result.go
> +	CoprCacheHit     int64
How about renaming this field to `CoprCacheHitNum` or `CoprCacheNumHit`?
`selectResultRuntimesStats.CoprCacheHit` and `CopRuntimeStats.CoprCacheHit` having the same name but different types seems ambiguous.

2020-09-11 06:45 UTC, qw4990 reviewed
LGTM

2020-09-14 03:59 UTC, nullnotnil requested changes
I would call this a hit ratio, rather than a rate. These are often used interchangeably, but I try to be careful to use _rate_ to refer to the number of misses over a time scale. i.e. 123 misses/s

**Edit:** Google seems to back me on this one. A rate is for comparing different units (such as _cache misses over time_):

> A ratio is a comparison of two numbers or measurements. The numbers or measurements being compared are called the terms of the ratio. A rate is a special ratio in which the two terms are in different units.

2020-09-14 05:29 UTC, lzmhhh123 commented
> I would call this a hit ratio, rather than a rate. These are often used interchangeably, but I try to be careful to use _rate_ to refer to the number of misses over a time scale. i.e. 123 misses/s
> 
> **Edit:** Google seems to back me on this one. A rate is for comparing different units (such as _cache misses over time_):
> 
> > A ratio is a comparison of two numbers or measurements. The numbers or measurements being compared are called the terms of the ratio. A rate is a special ratio in which the two terms are in different units.

Nice catch.

2020-09-14 05:38 UTC, nullnotnil approved these changes

2020-09-14 06:10 UTC, crazycs520 reviewed
LGTM

2020-09-14 06:10 UTC, crazycs520 approved these changes

2020-09-14 06:10 UTC, lzmhhh123 commented
/merge

2020-09-14 06:40 UTC, merged