executor, expression: fix question that sql results of function REGEXP are inconsistent with MySQL
pingcap/tidb pull request #20371
Opened 2020-10-09 09:33 UTC by xiaodong-ji

### What problem does this PR solve?

Issue Number: close #20060

Problem Summary: These sql results of function REGEXP are inconsistent with MySQL.

### What is changed and how it works?

What's Changed: If there are double '[' or ']' in the pattern, eg: '[[.~.]]', remove one of them.

### Check List

Tests

- Unit test

### Release note

- fix question that sql results of function REGEXP are inconsistent with MySQL

2020-10-09 11:09 UTC, wjhuang2016 commented
> If there are double '[' or ']' in the pattern, eg: '[[.~.]]', remove one of them.

@xiaodong-ji Hi, thank you for your contribution, could you provide some information about this change?
I mean, though MySQL's result looks like that it's true, we have better confirm it from the document or source code.

2020-10-10 01:36 UTC, xiaodong-ji commented
> > If there are double '[' or ']' in the pattern, eg: '[[.~.]]', remove one of them.
> 
> @xiaodong-ji Hi, thank you for your contribution, could you provide some information about this change?
> I mean, though MySQL's result looks like that it's true, we have better confirm it from the document or source code.

I seem to have only found this information (` [[=o=]], [[=(+)=]], and [o(+)] are all synonymous`) in the follow document.

2020-10-15 07:00 UTC, time-and-fate reviewed
Thanks for your contributions.
Seems like your change will make `SELECT 'z' REGEXP '[[:alpha:]]';` return 0, which currently is and should be 1.
I think simply change `[[...]]` to `[...]` isn't a proper method to solve the issue.

2020-10-15 07:59 UTC, xiaodong-ji commented
> Thanks for your contributions.
> Seems like your change will make `SELECT 'z' REGEXP '[[:alpha:]]';` return 0, which currently is and should be 1.
> I think simply change `[[...]]` to `[...]` isn't a proper method to solve the issue.

You are right, is there any ideas to slove this problem.

2020-10-23 03:54 UTC, rebelice requested changes

2020-10-23 03:54 UTC, rebelice commented on expression/builtin_like.go
> +
It seems that your solution can't handle cases like `'\\[[\\]]'`.

2020-10-23 06:07 UTC, wjhuang2016 reviewed
In fact, it's very difficult to make REGEXP to be compatible with MySQL. Because the regexp library is different, and we need to consider Go's, Rust's, and C++'s library. I think we can ignore this compatible problem so far. But if you have any good idea, feel free to discuss with us.

2020-12-03 11:17 UTC, wjhuang2016 commented
@xiaodong-ji Hi, as I said before, it's very difficult to make REGEXP to be compatible with MySQL. And this PR's modification seems dangerous. We decide not to merge this PR, sorry for that.

2020-12-03 11:26 UTC, xiaodong-ji commented
> @xiaodong-ji Hi, as I said before, it's very difficult to make REGEXP to be compatible with MySQL. And this PR's modification seems dangerous. We decide not to merge this PR, sorry for that.

OK，it doesn't matter.

2020-12-03 14:51 UTC, closed without merging