timeutil: fix unknown time zone 'posixrules'
pingcap/tidb pull request #20560
Opened 2020-10-21 06:53 UTC by lzmhhh123

### What problem does this PR solve?

Issue Number: close #15722 and close #20545

### What is changed and how it works?

How it Works: when get timezone from the system file, only step once soft link.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- fix unknown time zone 'posixrules'.

2020-10-21 06:58 UTC, lzmhhh123 commented
/run-all-tests

2020-10-21 07:03 UTC, lzmhhh123 commented
/run-all-tests

2020-10-21 07:13 UTC, lzmhhh123 commented
/run-unit-test

2020-10-21 15:15 UTC, ichn-hu requested changes
Rest LGTM

2020-10-21 15:15 UTC, ichn-hu commented on util/timeutil/time.go
> +func InferOneStepLinkForPath(path string) (string, error) {
Why this function is exported? It seems not necessary.

2020-10-22 07:19 UTC, ichn-hu approved these changes
LGTM

2020-10-23 08:23 UTC, qw4990 approved these changes
LGTM

2020-10-23 08:23 UTC, qw4990 commented
/merge

2020-10-23 08:33 UTC, merged