hptc ycsb-worloade: Make use of AppendRows in all cases
pingcap/tidb pull request #21163
Opened 2020-11-20 04:08 UTC by watchpoints

htpc ，after  [#pull/21057](https://github.com/pingcap/tidb/pull/21057)

### What problem does this PR solve?

Issue Number: close #20841  

Problem Summary:

### What is changed and how it works?

Find all AppendRows cases in TiDB, and make use of the new api. Make sure all tests are not effected.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No

2020-11-20 07:26 UTC, xhebox commented
/reward 300

2020-11-20 07:32 UTC, xhebox commented
/reward 300

2020-11-20 07:49 UTC, xhebox commented
/reward 300

2020-11-20 07:59 UTC, xhebox commented
/reward 300

2020-11-20 08:11 UTC, xhebox commented
/reward 300

2020-11-23 09:47 UTC, SunRunAway commented
`git grep AppendRow` shows the usage of `AppendRow` in such places, could these be improved?

executor/adapter.go:		chk.AppendRow(c.rows[c.idx])
executor/admin.go:					req.AppendRow(row)
executor/apply_cache_test.go:		value[i].AppendRow(srcRow)
executor/distsql.go:			req.AppendRow(resultTask.rows[resultTask.cursor])
executor/executor.go:			req.AppendRow(e.inputRow)
executor/executor.go:				chk.AppendRow(e.inputRow)
executor/executor.go:			e.virtualTableChunkList.AppendRow(mutableRow.ToRow())
executor/executor_required_rows_test.go:		req.AppendRow(r.genOneRow())
executor/index_merge_reader.go:			req.AppendRow(resultTask.rows[resultTask.cursor])
executor/join.go:				e.innerList.AppendRow(row)
executor/joiner.go:	// Call AppendRow() first to increment the virtual rows.
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(lhs, lUsed)
executor/joiner.go:		chk.AppendRowByColIdxs(outer, j.lUsed) // TODO: need test numVirtualRow
executor/joiner.go:			chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:			chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:			chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:		chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(outer, j.lUsed)
executor/joiner.go:	lWide := chk.AppendRowByColIdxs(j.defaultInner, j.lUsed)
executor/memtable_reader.go:		req.AppendRow(mutableRow.ToRow())
executor/parallel_apply.go:				e.innerList[id].AppendRow(row)
executor/show.go:		e.result.AppendRow(row)
executor/show.go:		e.result.AppendRow(row)
executor/shuffle.go:			results[workerIdx].AppendRow(chk.GetRow(i))
executor/sort.go:			req.AppendRow(row)
executor/sort.go:		req.AppendRow(partitionPtr.row)
executor/sort.go:		req.AppendRow(row)
executor/sort.go:			e.rowPtrs[0] = e.rowChunks.AppendRow(childRowChk.GetRow(i))
executor/sort.go:		newRowPtr := newRowChunks.AppendRow(e.rowChunks.GetRow(rowPtr))
executor/table_readers_required_rows_test.go:		chk.AppendRow(r.genOneRow())
executor/union_scan.go:			req.AppendRow(mutableRow.ToRow())
statistics/histogram.go:		newHist.Bounds.AppendRow(oldHist.Bounds.GetRow(boundIdx))
statistics/histogram.go:		newHist.Bounds.AppendRow(oldHist.Bounds.GetRow(boundIdx + 1))
statistics/histogram.go:			newIndexHist.Bounds.AppendRow(idx.Bounds.GetRow(i * 2))
statistics/histogram.go:			newIndexHist.Bounds.AppendRow(idx.Bounds.GetRow(i*2 + 1))
util/chunk/chunk.go:// AppendRow appends a row to the chunk.
util/chunk/chunk.go:func (c *Chunk) AppendRow(row Row) {
util/chunk/chunk.go:// AppendRowByColIdxs appends a row by its colIdxs to the chunk.
util/chunk/chunk.go:func (c *Chunk) AppendRowByColIdxs(row Row, colIdxs []int) (wide int) {
util/chunk/chunk_test.go:		chk2.AppendRow(row)
util/chunk/chunk_test.go:	// AppendRowByColIdxs and AppendPartialRowByColIdxs can do projection from row.
util/chunk/chunk_test.go:	chk.AppendRowByColIdxs(row, []int{3})
util/chunk/chunk_test.go:	chk.AppendRowByColIdxs(row, []int{1})
util/chunk/chunk_test.go:	chk.AppendRowByColIdxs(row, []int{})
util/chunk/chunk_test.go:func BenchmarkAppendRow(b *testing.B) {
util/chunk/chunk_test.go:		chk.AppendRow(row)
util/chunk/chunk_util_test.go:		dstChk.AppendRow(srcChk.GetRow(i))
util/chunk/chunk_util_test.go:		dstChk.AppendRow(srcChk.GetRow(i))
util/chunk/chunk_util_test.go:		dstChk.AppendRow(srcChk.GetRow(i))
util/chunk/chunk_util_test.go:			dstChk.AppendRow(srcChk.GetRow(j))
util/chunk/disk.go:		chk.AppendRow(row)
util/chunk/iterator_test.go:		ptr := li.AppendRow(chk.GetRow(i))
util/chunk/iterator_test.go:		ptr2 := li2.AppendRow(chk.GetRow(i))
util/chunk/list.go:// AppendRow appends a row to the List, the row is copied to the List.
util/chunk/list.go:func (l *List) AppendRow(row Row) RowPtr {
util/chunk/list.go:	chk.AppendRow(row)
util/chunk/list_test.go:		l.AppendRow(srcRow)
util/chunk/list_test.go:		l.AppendRow(srcRow)
util/chunk/list_test.go:	ptr := l.AppendRow(srcRow)
util/chunk/list_test.go:		l.AppendRow(tmp.GetRow(0))
util/chunk/list_test.go:	list.AppendRow(srcChk.GetRow(0))
util/chunk/list_test.go:		srcList.AppendRow(srcChk.GetRow(i))
util/chunk/list_test.go:		list.AppendRow(row)
util/chunk/row.go:	newChk.AppendRow(r)

2020-11-27 06:31 UTC, TszKitLo40 reviewed
Can we make the comment of these two functions more clearly?

2020-11-27 06:50 UTC, TszKitLo40 requested changes
This commented code can be deleted.

2020-11-27 06:50 UTC, TszKitLo40 commented on executor/admin.go
>  		for row := iter.Begin(); row != iter.End(); row = iter.Next() {
This code should be deleted

2020-11-27 06:51 UTC, TszKitLo40 reviewed
ditto

2020-11-27 06:51 UTC, TszKitLo40 commented on executor/sort.go
>  	for !req.IsFull() && e.Idx < len(e.rowPtrs) {
ditto

2020-11-27 07:11 UTC, watchpoints commented on executor/sort.go
>  	for !req.IsFull() && e.Idx < len(e.rowPtrs) {
yes. I   compared  to change code.

2020-11-27 08:13 UTC, xhebox requested changes

2020-11-27 08:13 UTC, xhebox commented on executor/sort.go
> +		for index < numToAppend {
What about`for index := 0; index < numToAppend; index++`?

2020-11-27 08:13 UTC, xhebox commented on executor/sort.go
> +			rows[index] = row
Suggest `rows[index] = e.rowChunks.GetRow(e.rowPtrs[e.Idx])`.
BTW, this one looks like a shared chunk, @TszKitLo40, and can apply the optimization in #21189 .

2020-11-27 08:13 UTC, xhebox commented on executor/memtable_reader.go
> +
Revert this line, just keep it unchanged.

2020-11-29 05:01 UTC, mmyj commented
LGTM

2020-11-29 08:08 UTC, wshwsh12 reviewed
LGTM

2020-11-29 08:09 UTC, wshwsh12 commented
/merge

2020-11-29 08:21 UTC, merged