executor: modify lookupTableTask to return merged rows, and improve AppendRows
pingcap/tidb pull request #21189
Opened 2020-11-22 13:40 UTC by TszKitLo40

### What problem does this PR solve?

Issue Number: close #20843 

Problem Summary:

### What is changed and how it works?

What's Changed:
modify lookupTableTask to return merged rows, and improve AppendRows
How it Works:
Modify lookupTableTask to return merged rows(maybe a chunk), gc may be improved by less live objects, AppendRows may make use of this feature to append data more efficiently.

### Check List 

Tests 

- Unit test

### Release note 

- No release note

2020-11-24 15:29 UTC, xhebox commented
/reward 600

2020-11-26 04:21 UTC, b41sh commented
/run-all-tests

2020-11-26 06:15 UTC, TszKitLo40 commented
/run-all-tests

2020-11-26 08:58 UTC, TszKitLo40 commented
/run-all-tests

2020-11-26 10:30 UTC, TszKitLo40 commented
/run-all-tests

2020-11-26 10:43 UTC, TszKitLo40 commented
/run-integration-common-test

2020-11-26 10:49 UTC, TszKitLo40 commented
/run-integration-common-test

2020-11-26 11:21 UTC, xhebox requested changes

2020-11-26 11:21 UTC, xhebox commented on executor/distsql.go
> +	if handleCnt != task.numRows && !util.HasCancelled(ctx) {
You can add methods GetNumRows and GetRow for task, to share code here.

2020-11-26 11:21 UTC, xhebox commented on util/chunk/chunk.go
> +// GetNumRows encapsulate NumRows and avoid chunk is nil.
Just check nil pointer by the caller rather than here.

2020-12-01 03:46 UTC, wshwsh12 commented on executor/distsql.go
> +	if w.keepOrder {
Why we need to distinguish keep-order or non-keep-order?

2020-12-01 07:15 UTC, arronliu1989 commented
/lgtm

2020-12-01 08:22 UTC, b41sh commented on executor/distsql.go
> +		task.chk = chunk.Renew(task.rows[0].Chunk(), task.rows[0].Chunk().NumRows())
renew a `Chunk` here will take up extra memory space, which may lead to worse performance.

2020-12-01 08:22 UTC, b41sh commented on executor/distsql.go
> +	}
We can build `task.chk` here, if `w.keepOrder` is  false.

2020-12-23 07:38 UTC, wshwsh12 commented
Could we close this PR now?

2020-12-23 09:47 UTC, b41sh commented
> Could we close this PR now?

Optimization performance is not good, we can close this pr.

2020-12-23 11:09 UTC, closed without merging