*: make rollback work on user-defined variables
pingcap/tidb pull request #21334
Opened 2020-11-26 12:12 UTC by tiancaiamao

### What problem does this PR solve?

Partly fix https://github.com/pingcap/tidb/issues/8393

Problem Summary:

`set @xx = yy` take effect immediately in TiDB, while in MySQL this statement can be rollbacked.

### What is changed and how it works?

What's Changed:

Make rollback work on user-defined variables.

How it Works:

Use struct `userDefinedVars` for user-defined variables.
This struct consists of a slice and a map, before commit, the modification is cached in the slice.
It has the `Commit` and `Rollback` methods to flush or drop the cached variables.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- make rollback work on user-defined variables

2020-11-27 07:15 UTC, tiancaiamao commented
PTAL @XuHuaiyu @lzmhhh123

2021-06-21 09:26 UTC, tiancaiamao commented
Hi, @morgo 
What's your opinion about this behaviour change?
Should we try to achieve the MySQL compatibility here? this behaviour change may also break the compatibility if we upgrade from an old TiDB cluster ...

2021-06-21 13:28 UTC, AilinKid commented on sessionctx/variable/session.go
> +func (udv *userDefinedVars) Get(name string) (types.Datum, bool) {
will it be concurrent access in the future?

2021-06-21 13:29 UTC, AilinKid reviewed
Rest LGTM

2021-06-21 15:11 UTC, mjonss commented
User variables are *not* transactional in MySQL:
```sql
mysql> select @testvar;
+--------------------+
| @testvar           |
+--------------------+
| NULL               |
+--------------------+
1 row in set (0,00 sec)

mysql> begin;
Query OK, 0 rows affected (0,00 sec)

mysql> set @testvar = 1;
Query OK, 0 rows affected (0,00 sec)

mysql> rollback;
Query OK, 0 rows affected (0,00 sec)

mysql> select @testvar;
+----------+
| @testvar |
+----------+
|        1 |
+----------+
1 row in set (0,00 sec)

mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 8.0.25-0ubuntu0.21.04.1 |
+-------------------------+
1 row in set (0,00 sec)

```

Neither are session or global variables in MySQL.
So I don't think making it transactional in TiDB makes sense, unless it is a requested feature and have its own flag for enable the compatibility breaking feature.

I also added a comment to https://github.com/pingcap/tidb/issues/8393

2021-06-21 15:12 UTC, mjonss requested changes
Although the patch seems good, it is based on the assumption that user variables *should* be transactional, when they are in fact *not* transactional in MySQL.

So I don't think we should push this change into TiDB and break the compatibility with MySQL.

2021-06-22 01:41 UTC, closed without merging