修复聚合函数min/max for enum/set不兼容mysql的bug#21451
pingcap/tidb pull request #21566
Opened 2020-12-08 11:08 UTC by StoneDotYang

### What problem does this PR solve?

Issue Number: close #21451  

Problem Summary: Aggregation `MIN/MAX` for `ENUM/SET` is incompatible with MySQL

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
For GetCompareFunc function, a new function genCmpNameValueFunc  with paramters collation is added to replace the original method cmpNameValue.

the function genCmpNameValueFunc return a handle func(l Row, lCol int, r Row, rCol int) int

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

2020-12-08 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/tidb?pullRequest=21566) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/tidb?pullRequest=21566) before we can accept your contribution.<br/><hr/>**shaoyu.yang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/tidb?pullRequest=21566) it.</sub>

2020-12-09 13:49 UTC, XuHuaiyu commented
- Thanks for your contribution. Is this PR ready to be reviewed?
- Please add some test case

2020-12-13 04:59 UTC, b41sh commented
As `CompareFunc` is used both by `SortExec` and `TopNExec`, we can't modify `GetCompareFunc` directly. Maybe we can add a function like `GetCompareTopNFunc` to generate compare function for `TopNExec` seperately. And please add some test functions for this case.

2020-12-14 07:13 UTC, XuHuaiyu commented
Add some test cases in `executor/executor_test.go`, we can add a function like `TestIssue21451`

2020-12-14 07:14 UTC, XuHuaiyu commented
PTAL @b41sh

2020-12-14 13:36 UTC, b41sh commented on util/chunk/compare.go
> +// GetCompareTopNFunc get compare funcs by their string value For MAX()/Min() on ENUM and SET field type
how about modify comment as follow:
// GetCompareTopNFunc gets a compare function for the field type used by TopNExec
// as EnumSet field type is sorted by name in TopNExec, but by value in SortExec

2020-12-14 13:45 UTC, b41sh commented on executor/executor_test.go
> +
We'd better move this blank line up one line.

2020-12-14 16:30 UTC, pingyu commented
1. `MAX/MIN` for `SET` is implemented [here](https://github.com/pingcap/tidb/blob/ab9cd019be921b4d7ece3cca883b7cac7796e314/executor/aggfuncs/func_max_min.go#L1413). It is not related to `SORT`.

2. Result of `ORDER BY` on `SET` seems to be the same as mysql (compared on relative position in the set. Codes are [here](https://github.com/pingcap/tidb/blob/ab9cd019be921b4d7ece3cca883b7cac7796e314/util/chunk/compare.go#L49)). I think we don't need to modify `SortExec`/`TopNExec`

  * mysql
```sql
mysql> create table t5(en enum('c', 'b', 'a'));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t5 values ('a'), ('b'), ('c');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from t5 order by en;
+------+
| en   |
+------+
| c    |
| b    |
| a    |
+------+
3 rows in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.00 sec)
```

  * TiDB master:
```sql
mysql root@localhost:test> create table t5(en enum('c', 'b', 'a'));                                                                                                                                          
Query OK, 0 rows affected
Time: 0.006s
mysql root@localhost:test> insert into t5 values ('a'), ('b'), ('c');                                                                                                                                         
Query OK, 3 rows affected
Time: 0.005s
mysql root@localhost:test> select * from t5 order by en;                                                                                                                                                      
+----+
| en |
+----+
| c  |
| b  |
| a  |
+----+
3 rows in set
Time: 0.014s
mysql root@localhost:test> select tidb_version();                                                                                                                                                              
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1804-g06cd92e05                    |
| Edition: Community                                                |
| Git Commit Hash: 06cd92e05f0dfff1a139c1e5baca2ee24fb387b2         |
| Git Branch: master                                                |
| UTC Build Time: 2020-12-13 14:20:29                               |
| GoVersion: go1.13.8                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: true                                     |
+-------------------------------------------------------------------+
1 row in set
Time: 0.014s
mysql root@localhost:test>  
```

3. It seems that this issue is introduced by me (#19552) ...I'm so sorry...

2020-12-15 00:24 UTC, b41sh commented
@pingyu  from explain info we can see that `StreamAgg` get chunk data from `TopNExec`.
Currently both `SortExec` and `TopNExec` use `initCompareFuncs()` to get compare function, but for `enum/set` field the behavior of `sort by` and `min/max` are diff, so we must modfiy `initCompareFuncs()`

```
mysql> explain select min(en) from t5;
+------------------------------+----------+-----------+---------------+---------------------------------+
| id                           | estRows  | task      | access object | operator info                   |
+------------------------------+----------+-----------+---------------+---------------------------------+
| StreamAgg_13                 | 1.00     | root      |               | funcs:min(test.t5.en)->Column#3 |
| └─TopN_16                    | 1.00     | root      |               | test.t5.en, offset:0, count:1   |
|   └─Selection_20             | 8000.00  | root      |               | not(isnull(test.t5.en))         |
|     └─TableReader_22         | 10000.00 | root      |               | data:TableFullScan_21           |
|       └─TableFullScan_21     | 10000.00 | cop[tikv] | table:t5      | keep order:false, stats:pseudo  |
+------------------------------+----------+-----------+---------------+---------------------------------+
5 rows in set (0.00 sec)
```

2020-12-15 02:31 UTC, pingyu commented
Oh...I see.
But modification to `TopNExec` will affect `ORDER BY` too, which should be sorted by relative position.

BTW, `MAX`/`MIN` with `GROUP BY` clause doesn't have `TopN` executor.
```sql
mysql root@localhost:test> create table t6(id int, en enum('c', 'b', 'a'));                                                                                                                              
Query OK, 0 rows affected
Time: 0.023s
mysql root@localhost:test> explain select id, max(en) from t6 group by id;                                                                                                                               
+-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
| id                    | estRows  | task      | access object | operator info                                                                                |
+-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
| Projection_4          | 8000.00  | root      |               | test.t6.id, Column#4                                                                         |
| └─HashAgg_5           | 8000.00  | root      |               | group by:test.t6.id, funcs:max(test.t6.en)->Column#4, funcs:firstrow(test.t6.id)->test.t6.id |
|   └─TableReader_9     | 10000.00 | root      |               | data:TableFullScan_8                                                                         |
|     └─TableFullScan_8 | 10000.00 | cop[tikv] | table:t6      | keep order:false, stats:pseudo                                                               |
+-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
4 rows in set
Time: 0.011s
mysql root@localhost:test>  
```

2020-12-15 04:31 UTC, b41sh commented
> Oh...I see.
> But modification to `TopNExec` will affect `ORDER BY` too, which should be sorted by relative position.
> 
> BTW, `MAX`/`MIN` with `GROUP BY` clause doesn't have `TopN` executor.
> 
> ```sql
> mysql root@localhost:test> create table t6(id int, en enum('c', 'b', 'a'));                                                                                                                              
> Query OK, 0 rows affected
> Time: 0.023s
> mysql root@localhost:test> explain select id, max(en) from t6 group by id;                                                                                                                               
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | id                    | estRows  | task      | access object | operator info                                                                                |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | Projection_4          | 8000.00  | root      |               | test.t6.id, Column#4                                                                         |
> | └─HashAgg_5           | 8000.00  | root      |               | group by:test.t6.id, funcs:max(test.t6.en)->Column#4, funcs:firstrow(test.t6.id)->test.t6.id |
> |   └─TableReader_9     | 10000.00 | root      |               | data:TableFullScan_8                                                                         |
> |     └─TableFullScan_8 | 10000.00 | cop[tikv] | table:t6      | keep order:false, stats:pseudo                                                               |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> 4 rows in set
> Time: 0.011s
> mysql root@localhost:test>  
> ```

ok, we also need to modify `maxMin4Enum` and `maxMin4Set`

2020-12-17 02:45 UTC, XuHuaiyu commented
@StoneDotYang Do you have any problem addressing [this comment](https://github.com/pingcap/tidb/pull/21566#issuecomment-745044985)?

2020-12-17 03:06 UTC, StoneDotYang commented
> Oh...I see.
> But modification to `TopNExec` will affect `ORDER BY` too, which should be sorted by relative position.
> 
> BTW, `MAX`/`MIN` with `GROUP BY` clause doesn't have `TopN` executor.
> 
> ```sql
> mysql root@localhost:test> create table t6(id int, en enum('c', 'b', 'a'));                                                                                                                              
> Query OK, 0 rows affected
> Time: 0.023s
> mysql root@localhost:test> explain select id, max(en) from t6 group by id;                                                                                                                               
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | id                    | estRows  | task      | access object | operator info                                                                                |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | Projection_4          | 8000.00  | root      |               | test.t6.id, Column#4                                                                         |
> | └─HashAgg_5           | 8000.00  | root      |               | group by:test.t6.id, funcs:max(test.t6.en)->Column#4, funcs:firstrow(test.t6.id)->test.t6.id |
> |   └─TableReader_9     | 10000.00 | root      |               | data:TableFullScan_8                                                                         |
> |     └─TableFullScan_8 | 10000.00 | cop[tikv] | table:t6      | keep order:false, stats:pseudo                                                               |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> 4 rows in set
> Time: 0.011s
> mysql root@localhost:test>  
> ```

hi,pingyu, I modified the func_max_min.go,

> @StoneDotYang Do you have any problem addressing [this comment](https://github.com/pingcap/tidb/pull/21566#issuecomment-745044985)?

I am modifying the test case

2020-12-17 11:17 UTC, b41sh commented
please fix the test @StoneDotYang

2020-12-18 04:13 UTC, StoneDotYang commented
> please fix the test @StoneDotYang

yeah,has modified the related test case.

2020-12-18 05:12 UTC, b41sh commented
/run-all-tests

2020-12-18 06:03 UTC, b41sh commented
LGTM

2020-12-18 06:05 UTC, b41sh commented
@pingyu  PTAL

2020-12-18 07:00 UTC, wshwsh12 reviewed
It seems TopN for enum will get a wrong result..   
```
MySQL [test]> create table t(e enum('e','d','c','b','a'));
Query OK, 0 rows affected (0.010 sec)

MySQL [test]> insert into t values('e'),('d'),('c'),('b'),('a');
Query OK, 5 rows affected (0.003 sec)
Records: 5  Duplicates: 0  Warnings: 0

MySQL [test]> select * from t order by e limit 1;
+------+
| e    |
+------+
| e    |
+------+
1 row in set (0.000 sec)
```
But this pr will get a result `a`.

2020-12-18 07:41 UTC, b41sh commented
> It seems TopN for enum will get a wrong result..
> 
> ```
> MySQL [test]> create table t(e enum('e','d','c','b','a'));
> Query OK, 0 rows affected (0.010 sec)
> 
> MySQL [test]> insert into t values('e'),('d'),('c'),('b'),('a');
> Query OK, 5 rows affected (0.003 sec)
> Records: 5  Duplicates: 0  Warnings: 0
> 
> MySQL [test]> select * from t order by e limit 1;
> +------+
> | e    |
> +------+
> | e    |
> +------+
> 1 row in set (0.000 sec)
> ```
> 
> But this pr will get a result `a`.

it seems the behavior of enum for MySQL is mixed. 
`select * from t order by e;` is ordered by value, but `select max(e) from t;` is ordered by name.
so we can't use `TopNExec` when the field type is `enum/set` for `max/min` agg functions.

2020-12-18 07:45 UTC, wshwsh12 commented
> we can't use TopNExec when the field type is enum/set for max/min agg functions.

Yes, I think you are right.

2020-12-18 07:48 UTC, b41sh commented
LGTM  cancel

2020-12-18 14:28 UTC, b41sh requested changes

2020-12-18 14:28 UTC, b41sh commented on planner/core/rule_max_min_eliminate.go
> +
please add some comment for this case

2020-12-18 14:30 UTC, b41sh commented
please fix the conflict @StoneDotYang

2020-12-18 15:28 UTC, StoneDotYang commented
/run-all-tests

2020-12-19 07:50 UTC, StoneDotYang commented
/run-all-tests

2020-12-19 07:59 UTC, StoneDotYang commented
/run-all-tests

2020-12-21 07:42 UTC, b41sh commented on planner/core/rule_max_min_eliminate.go
> +		// Limit+Sort operators are sorted by value,but ENUM/SET field types are sorted by name.
please put a space after the comma

2020-12-21 07:51 UTC, StoneDotYang commented on planner/core/rule_max_min_eliminate.go
> +		// Limit+Sort operators are sorted by value,but ENUM/SET field types are sorted by name.
ok.has add space.PTAL

2020-12-21 08:10 UTC, wshwsh12 reviewed
LGTM

2020-12-21 08:14 UTC, b41sh commented
LGTM

2020-12-21 08:47 UTC, lzmhhh123 commented
/merge

2020-12-21 09:07 UTC, merged