expression: fix unexpect invalid json text error when query with `json_extract`
pingcap/tidb pull request #21720
Opened 2020-12-14 10:13 UTC by TszKitLo40

### What problem does this PR solve?

Issue Number: close #11883  

Problem Summary:

### What is changed and how it works?

What's Changed:
fix unexpect invalid json text error when query with `json_extract`
How it Works:
When a string can't be casted to json, use `json.CreateBinary`
### Related changes

### Check List 

Tests 

- Integration test

### Release note 

- No release note

2020-12-15 10:56 UTC, ichn-hu requested changes
Also please add some test cases.

2020-12-15 10:56 UTC, ichn-hu commented on expression/builtin_cast.go
> +	if mysql.HasParseToJSONFlag(b.tp.Flag) && json2.Valid(data) {
Probabily we don't need use `encoding/json` to check the validity, just ParseBInaryFromString and if err is not nil we will fall back to CreateBinary?

2020-12-15 11:00 UTC, ichn-hu commented
@TszKitLo40 Also, would you please check if your PR could fix https://github.com/pingcap/tidb/issues/13710 ?

2020-12-15 11:04 UTC, TszKitLo40 commented
> #13710

I am not sure whether it is the best choice to fix this issue, because it make cause some test case fail. Do you think we can should cast a common string to json?

2020-12-15 11:06 UTC, TszKitLo40 commented
> @TszKitLo40 Also, would you please check if your PR could fix #13710 ?

I am not sure whether it is the best choice to fix this issue, because it make cause some test case fail. Do you think we can should cast a common string to json?

2020-12-15 11:26 UTC, TszKitLo40 commented
> @TszKitLo40 Also, would you please check if your PR could fix #13710 ?

And I aslo have test [#13710](https://github.com/pingcap/tidb/issues/13710), it use the same logic `json.ParseBinaryFromString` to parse a string to json, but it is used in the `vecEvalJSON` of `*builtinCastStringAsJSONSig`, if we decide to use the this PR to fix it, we can use the fix it in the same way in `vecEvalJSON`.

2020-12-15 11:33 UTC, TszKitLo40 commented
> Also please add some test cases.

I am not sure whether it is the best choice to fix this issue, because it make cause some test case fail. Do you think we can should cast a common string to json? And maybe `HasParseToJSONFlag` should be set to false here.  @ichn-hu

2020-12-15 12:12 UTC, ichn-hu commented
I am not sure as well, but I do have concerns about implicit type conversion, perhaps we need to investigate more on MySQLs behavior and to find out if it really a valid fix.

Examples like

* compare with valid json
* compare with invalid json 
* compare with mixed valid and invalid json

2020-12-15 12:14 UTC, TszKitLo40 commented
> I am not sure as well, but I do have concerns about implicit type conversion, perhaps we need to investigate more on MySQLs behavior and to find out if it really a valid fix.
> 
> Examples like
> 
> * compare with valid json
> * compare with invalid json
> * compare with mixed valid and invalid json

But in this case, it seems that we must cast a string to json.

2020-12-17 03:43 UTC, ichn-hu commented
> > I am not sure as well, but I do have concerns about implicit type conversion, perhaps we need to investigate more on MySQLs behavior and to find out if it really a valid fix.
> > Examples like
> > 
> > * compare with valid json
> > * compare with invalid json
> > * compare with mixed valid and invalid json
> 
> But in this case, it seems that we must cast a string to json. I don't know why do we need to check `HasParseToJSONFlag` here.

I think it is not always the case, if there is an invalid json string in the argument lists, MySQL would not convert it into json.

```
create table t1(f1 json);
insert into t1(f1) values ('"asd"'),('"asdf"'),('"asasas"');
select f1 from t1 where json_extract(f1,"$") in ("asd","asasas","{asdf");
+----------+
| f1       |
+----------+
| "asd"    |
| "asasas" |
+----------+
```

2020-12-17 03:50 UTC, TszKitLo40 commented
> > > I am not sure as well, but I do have concerns about implicit type conversion, perhaps we need to investigate more on MySQLs behavior and to find out if it really a valid fix.
> > > Examples like
> > > 
> > > * compare with valid json
> > > * compare with invalid json
> > > * compare with mixed valid and invalid json
> > 
> > 
> > But in this case, it seems that we must cast a string to json. I don't know why do we need to check `HasParseToJSONFlag` here.
> 
> I think it is not always the case, if there is an invalid json string in the argument lists, MySQL would not convert it into json.
> 
> ```
> create table t1(f1 json);
> insert into t1(f1) values ('"asd"'),('"asdf"'),('"asasas"');
> select f1 from t1 where json_extract(f1,"$") in ("asd","asasas","{asdf");
> +----------+
> | f1       |
> +----------+
> | "asd"    |
> | "asasas" |
> +----------+
> ```

It seems that it is hard to know whether we should convert the string to json.

2020-12-17 03:51 UTC, ichn-hu commented
Note that 

```
drop table t1;
create table t1(f1 json);
insert into t1 values ('{"a": "asdf"}');
select json_extract(f1, '$') from t1;
select f1 from t1 where json_extract(f1, '$') in ('{"a": "asdf"}');
```

will produce 0 row in MySQ, and only

```
select f1 from t1 where json_extract(f1, '$') in (cast('{"a": "asdf"}' as json));
```

will do the work.

So I think the fix is not to convert string to json, instead, we can

* if both are json type, then compare them directly
* if we want to compare json with string, convert json to string if tpCode is string, otherwise return false directly.

2020-12-17 03:56 UTC, TszKitLo40 commented
> Note that
> 
> ```
> drop table t1;
> create table t1(f1 json);
> insert into t1 values ('{"a": "asdf"}');
> select json_extract(f1, '$') from t1;
> select f1 from t1 where json_extract(f1, '$') in ('{"a": "asdf"}');
> ```
> 
> will produce 0 row in MySQL, and only
> 
> ```
> select f1 from t1 where json_extract(f1, '$') in (cast('{"a": "asdf"}' as json));
> ```
> 
> will do the work.
> 
> So I think the fix is not to convert string to json, instead, we can
> 
> * if both are json type, then compare them directly
> * if we want to compare json with string, convert json to string if tpCode is string, otherwise return false directly.

It seems resonable, but if we do that, it seems that we need to change the execution planner?

2020-12-17 04:02 UTC, ichn-hu commented
@TszKitLo40 Not necessarily, we could do it during runtime, just around the lines you were just changed.

2020-12-17 04:54 UTC, TszKitLo40 commented
> @TszKitLo40 Not necessarily, we could do it during runtime, just around the lines you just changed.

But in the lines I changed, we don't know the type of value to be compared, we need to know it so that we can decide whether we should cast it to json or keep it as string.

2020-12-17 06:27 UTC, ichn-hu commented
> > @TszKitLo40 Not necessarily, we could do it during runtime, just around the lines you just changed.
> 
> But in the lines I changed, we don't know the type of value to be compared, we need to know it so that we can decide whether we should cast it to json or keep it as string.

Yeah, I found that it need to change planner. If you don't mind, I would like to take over this issue (I've almost figured out the fix), but you are welcomed to look at other issues on #20804

2020-12-17 06:32 UTC, TszKitLo40 commented
> > > @TszKitLo40 Not necessarily, we could do it during runtime, just around the lines you just changed.
> > 
> > 
> > But in the lines I changed, we don't know the type of value to be compared, we need to know it so that we can decide whether we should cast it to json or keep it as string.
> 
> Yeah, I found that it need to change planner. If you don't mind, I would like to take over this issue (I've almost figured out the fix), but you are welcomed to look at other issues on #20804

OK, feel free to take over this issue. And I will close this PR.

2020-12-17 06:33 UTC, closed without merging