[WIP] Add start cluster in  run-tests.sh in globalkilltest
pingcap/tidb pull request #21851
Opened 2020-12-17 07:01 UTC by zhouqiang-cl

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Add start cluster in globalkilltest and make it happy in CI

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- None

### Check List 

Tests 

- No code, just modify test script

Side effects

- None

### Release note 

-

2020-12-17 07:57 UTC, zhouqiang-cl commented
/run-e2e-tests

2020-12-17 09:26 UTC, zhouqiang-cl commented
/run-check-release-note

2020-12-17 09:27 UTC, zhouqiang-cl commented
/run-check-title

2020-12-17 12:47 UTC, pingyu requested changes
Two small suggestions. Rest LGTM.

2020-12-17 12:47 UTC, pingyu commented on tests/globalkilltest/run-tests.sh
> +   ${TIDB} -P 5000 -status 8000 -store tikv -path "127.0.0.1:2379" &>tidb.log &
No need to start a TiDB here.
Will be started up in test cases.

2020-12-17 12:47 UTC, pingyu commented on tests/globalkilltest/run-tests.sh
> +   ${PD} --name=pd --data-dir=pd &>pd.log &
Delete `--pd <pd-client-path>: PD client path, ip:port list seperated by comma. Defaults to "127.0.0.1:2379".` in help message.

2020-12-17 12:57 UTC, pingyu commented
LGTM

2020-12-17 12:59 UTC, zhouqiang-cl commented
/run-e2e-tests

2020-12-18 03:55 UTC, SunRunAway reviewed
LGTM

2020-12-18 03:55 UTC, SunRunAway commented
/merge

2020-12-18 04:09 UTC, merged