select into outfile `untime error: index out of range`
pingcap/tidb pull request #22038
Opened 2020-12-25 13:02 UTC by jiyfhust

### What problem does this PR solve?

https://github.com/pingcap/tidb/issues/22023#ref-issue-735256507

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

2020-12-29 06:16 UTC, ichn-hu requested changes
Cool! Thanks for your contribution, would you please add some tests the reflect the correction?

2020-12-29 11:05 UTC, jiyfhust commented
> Cool! Thanks for your contribution, would you please add some tests the reflect the correction?

Please have a check again. 

 I run "make test", it fail in pkg ddl and executor. But i run "make testpkg pkg=ddl; make testpkg pkg=executor", it all passed.

2020-12-29 11:08 UTC, jiyfhust commented
No release note

2020-12-30 03:21 UTC, qw4990 commented
/run-all-tests

2020-12-30 03:34 UTC, qw4990 commented
/run-all-tests

2020-12-30 03:35 UTC, qw4990 reviewed
LGTM

2020-12-30 03:35 UTC, qw4990 commented
PTAL @ichn-hu

2020-12-30 03:38 UTC, qw4990 commented
/run-integration-compatibility-test

2020-12-30 06:33 UTC, XuHuaiyu approved these changes
LGTM

2020-12-30 06:34 UTC, XuHuaiyu commented
/merge

2020-12-30 06:49 UTC, merged