return warning when load data meet no partition for incompatiable mysql,but err and abort
pingcap/tidb pull request #22042
Opened 2020-12-27 15:02 UTC by StoneDotYang

### What problem does this PR solve?

Issue Number: close #21966 

Problem Summary:
load data into partition table shouldn't return no partition error
### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
when load data meet no partition, return toBeCheckedRow with err,but err returned directly in  function getKeysNeedCheckOneRow, file batch_checked.go and  append warning when noPartitionErr is not nil in batchCheckAndInsert func, file insert_common.go 

How it Works:
append warning when noPartitionErr is not nil in batchCheckAndInsert func, file insert_common.go 

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
when getPartitionByRow, if the data meet no partition, it return err directly.but should return warning for incompatiable mysql.

-

2020-12-29 08:36 UTC, StoneDotYang commented
/run-all-tests

2020-12-30 07:36 UTC, b41sh requested changes

2020-12-30 07:36 UTC, b41sh commented on server/server_test.go
> +		dbt.mustExec(fmt.Sprintf("load data local infile %q into table t", path))
please check err is nil 
`c.Assert(err, IsNil)`

2020-12-30 07:36 UTC, b41sh commented on server/server_test.go
> +		// As return warning when load data meet no partition error
this comment is meaningless, we can remove it.

2020-12-30 07:36 UTC, b41sh commented on server/server_test.go
>  		// Test load data meet no partition error.
this error is a warning now.

2020-12-30 07:36 UTC, b41sh commented on server/server_test.go
>  		// Test load data meet no partition error.
ditto

2020-12-30 07:36 UTC, b41sh commented on server/server_test.go
>  		// Test load data meet no partition error.
ditto

2020-12-30 07:37 UTC, b41sh commented on executor/executor.go
> +		sc.IgnoreNoPartition = true
please add a comment here.

2020-12-30 07:54 UTC, StoneDotYang commented on executor/executor.go
> +		sc.IgnoreNoPartition = true
tks，have fixed。

2020-12-30 10:43 UTC, b41sh commented
LGTM

2021-01-04 04:37 UTC, crazycs520 approved these changes
LGTM

2021-01-04 04:37 UTC, crazycs520 commented
/merge

2021-01-04 04:49 UTC, merged