executor: fix `subquery returns more than 1 row` if multi-rows are same
pingcap/tidb pull request #22194
Opened 2021-01-06 03:07 UTC by wjhuang2016

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #10151 

Problem Summary:
If the subquery return more than one rows and the rows are the same, we should not return an error.

### What is changed and how it works?

Save the first row for checking. And check if the rest rows are the same as the first row.
How it Works:

### Related changes

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Allow scalar subquery returns more than one row if these rows are same

2021-01-06 07:33 UTC, ichn-hu requested changes
Rest LGTM

2021-01-06 07:33 UTC, ichn-hu commented on executor/executor.go
> +		return row, err
Kind of curious who wrote the for loop here previously...

2021-01-07 09:50 UTC, ichn-hu submitted a review, later dismissed

2021-01-08 06:34 UTC, wshwsh12 commented on executor/executor.go
> +	if e.evaluated && len(e.rowData) == 0 {
Why we need check `len(e.rowData) == 0`? 
I think the logic after this line should only run once..

2021-01-08 06:34 UTC, wshwsh12 commented on executor/executor.go
> +			e.rowData = append(e.rowData, row.GetRaw(i))
IsNull is also should be check.

2021-01-08 08:50 UTC, wshwsh12 reviewed
LGTM

2021-01-08 09:16 UTC, ichn-hu approved these changes

2021-01-08 09:16 UTC, wshwsh12 approved these changes

2021-01-08 09:47 UTC, wjhuang2016 commented
/merge

2021-01-08 10:38 UTC, wjhuang2016 commented
/run-all-tests --tidb-test=pr/1151

2021-01-09 05:19 UTC, merged