*: open option to test tpch
pingcap/tidb pull request #23184
Opened 2021-03-09 03:13 UTC by wshwsh12

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

2021-03-11 08:19 UTC, XuHuaiyu commented on session/bootstrap.go
> +	mustExecute(s, "set @@global.tidb_track_aggregate_memory_usage = 1")
Add a test case for this.
Check the value in version65 and version66

2021-03-11 11:08 UTC, ichn-hu requested changes
Rest LGTM

2021-03-11 11:08 UTC, ichn-hu commented on session/bootstrap.go
> +	// version66 open the feature `track_aggregate_memory_usage` by default.
s/open/enable

2021-03-11 15:39 UTC, wshwsh12 commented on session/bootstrap.go
> +	// version66 open the feature `track_aggregate_memory_usage` by default.
Addressed.

2021-03-12 06:16 UTC, XuHuaiyu reviewed
LGTM

2021-03-12 06:38 UTC, ichn-hu approved these changes

2021-03-12 06:43 UTC, XuHuaiyu commented
/LGTM

2021-03-12 06:48 UTC, wshwsh12 commented
/merge

2021-03-12 07:13 UTC, wshwsh12 commented
/run-all-tests

2021-03-12 07:25 UTC, wshwsh12 commented
/run-unit-test

2021-03-12 07:35 UTC, wshwsh12 commented
/run-unit-test

2021-03-12 07:52 UTC, wshwsh12 commented
/run-all-tests

2021-03-12 09:16 UTC, wshwsh12 commented
/run-all-tests

2021-03-12 09:45 UTC, wshwsh12 commented
/rebuild

2021-03-12 09:46 UTC, wshwsh12 commented
/run-unit-test

2021-03-12 09:48 UTC, wshwsh12 commented
/run-all-tests

2021-03-12 09:59 UTC, merged