the value of tikv-client.copr-cache.capacity-mb should >=0
pingcap/tidb pull request #24232
Opened 2021-04-23 06:04 UTC by Howie59

### What problem does this PR solve?

Issue Number: close #24118
### What is changed and how it works?

### Check List 

Tests 
- Manual test (add detailed scripts or steps below)
- Side effects

### Release note 

- No release note

2021-04-23 07:36 UTC, wjhuang2016 commented on store/copr/coprocessor_cache.go
> +
Redundant empty line

2021-04-23 07:36 UTC, wjhuang2016 commented on store/copr/coprocessor_cache.go
> +		return nil, nil
Should return error

2021-04-28 06:37 UTC, djshow832 commented on store/copr/coprocessor_cache.go
> +	}
The error message is not clear enough for users. How about just merge this part into the judgement below?
`if capacityInBytes == 0` -> `if capacityInBytes <= 0`.

2021-04-29 02:55 UTC, Howie59 commented
/run-check_dev_2

2021-04-29 06:16 UTC, djshow832 commented
/lgtm

2021-05-03 03:23 UTC, mmyj requested changes

2021-05-03 03:23 UTC, mmyj commented on store/copr/coprocessor_cache.go
> +
Delete this empty line?

2021-05-03 04:03 UTC, mmyj commented
/lgtm

2021-05-06 02:27 UTC, Howie59 commented
/cc @djshow832

2021-05-06 02:55 UTC, wjhuang2016 commented
/lgtm

2021-05-06 02:55 UTC, wjhuang2016 commented
/merge

2021-05-06 03:05 UTC, merged