*: add builtin function ``json_pretty``
pingcap/tidb pull request #24675
Opened 2021-05-14 15:06 UTC by jianzhiyao

### What problem does this PR solve?

Issue Number: part of https://github.com/pingcap/tidb/issues/14486

Problem Summary:

add builtin function ``json_pretty``

### What is changed and how it works?

add builtin function ``json_pretty``

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- *: add builtin function ``json_pretty``

2021-05-14 15:20 UTC, jianzhiyao commented
/run-check_release_note

2021-05-14 16:58 UTC, morgo commented
@jiangyuzhao Thank you for adding this, it's very useful!

May I ask that you add some tests, such as:
- An integration test showing `json_pretty` applied on a column with the JSON data type.
- An integration test showing `json_pretty` applied to a varchar column (with inconsistent formatting)
- An integration test showing `json_pretty` applied to invalid JSON data, showing the same error as MySQL.

2021-05-15 14:00 UTC, jianzhiyao commented
I make some test in tidb and mysql.
And I found their behavior is different when applying to invalid JSON data, which seems belong to another compatibility problem.

2021-05-15 14:01 UTC, jianzhiyao commented
> @jiangyuzhao Thank you for adding this, it's very useful!
> 
> May I ask that you add some tests, such as:
> 
> * An integration test showing `json_pretty` applied on a column with the JSON data type.
> * An integration test showing `json_pretty` applied to a varchar column (with inconsistent formatting)
> * An integration test showing `json_pretty` applied to invalid JSON data, showing the same error as MySQL.

I make some test in tidb and mysql.
And I found their behavior is different when applying to invalid JSON data, which seems belong to another compatibility problem.

2021-05-17 01:54 UTC, morgo commented
> > @jiangyuzhao Thank you for adding this, it's very useful!
> > May I ask that you add some tests, such as:
> > 
> > * An integration test showing `json_pretty` applied on a column with the JSON data type.
> > * An integration test showing `json_pretty` applied to a varchar column (with inconsistent formatting)
> > * An integration test showing `json_pretty` applied to invalid JSON data, showing the same error as MySQL.
> 
> I make some test in tidb and mysql.
> And I found their behavior is different when applying to invalid JSON data, which seems belong to another compatibility problem.

Can you add the tests in the PR description to `expression/integration_test.go`. This will allow us to run the tests automatically. Thanks!

2021-05-17 05:34 UTC, jianzhiyao commented
/run-check_dev_2

2021-05-17 06:15 UTC, jianzhiyao commented
Integration tests is added, PTAL @morgo

2021-05-17 06:52 UTC, jianzhiyao commented
/run-check_dev

2021-05-17 07:00 UTC, jianzhiyao commented
PTAL @morgo

2021-05-17 19:49 UTC, morgo commented
LGTM (non binding)

Sorry, I am not a component/expression reviewer. I will bring it up in #sig-exec on TiDB community slack.

2021-05-18 09:21 UTC, lzmhhh123 approved these changes

2021-05-19 10:38 UTC, pingyu requested changes

2021-05-19 10:38 UTC, pingyu commented on expression/integration_test.go
> +		"{\n  \"a\": 1,\n  \"b\": \"qwe\",\n  \"c\": [\n    1,\n    2,\n    3,\n    \"123\",\n    null\n  ],\n  \"d\": {\n    \"d1\": 1,\n    \"d2\": 2\n  }\n}",
Nit: suggest using raw string literal for better readability, e.g.
```go
checkResult := []string{`{
    "a": 1,
    "b": "qwe",
    ...
}`,
...
```

2021-05-19 10:38 UTC, pingyu commented on expression/builtin_json_test.go
> +		{[]interface{}{`{"a":1,"b":[{"d":1},{"e":2},{"f":3}],"c":"eee"}`}, "{\n  \"a\": 1,\n  \"b\": [\n    {\n      \"d\": 1\n    },\n    {\n      \"e\": 2\n    },\n    {\n      \"f\": 3\n    }\n  ],\n  \
Nit: suggest using multiline raw string literal for better readability:
```go
`{
    "a": 1,
    "b": [
    ...
}`
```

2021-05-19 13:04 UTC, jianzhiyao commented
PTAL again @pingyu

2021-05-19 17:09 UTC, pingyu commented
/lgtm

2021-05-20 01:53 UTC, jianzhiyao commented
PTAL again @lzmhhh123

2021-05-20 06:16 UTC, lzmhhh123 approved these changes

2021-05-20 06:17 UTC, lzmhhh123 commented
/merge

2021-05-20 06:25 UTC, jianzhiyao commented
/run-common-test
/run-integration-common-test

2021-05-20 06:30 UTC, jianzhiyao commented
/run-common-test
/run-integration-common-test
/run-check_dev_2
/run-uint-test

2021-05-20 06:41 UTC, jianzhiyao commented
/run-common-test
/run-integration-common-test
/run-uint-test

2021-05-20 06:45 UTC, jianzhiyao commented
/run-uint-test

2021-05-20 06:47 UTC, jianzhiyao commented
/run-unit-test

2021-05-20 07:01 UTC, jianzhiyao commented
/run-uint-test

2021-05-20 07:04 UTC, jianzhiyao commented
/run-uint-test

2021-05-20 07:05 UTC, jianzhiyao commented
/run-unit-test

2021-05-20 07:36 UTC, jianzhiyao commented
/run-unit-test

2021-05-20 08:20 UTC, jianzhiyao commented
/run-unit-test

2021-05-20 08:31 UTC, jianzhiyao commented
Why the uint-test failed some many time? i can not get any useful info in error message
@lzmhhh123

2021-05-20 09:05 UTC, jianzhiyao commented
/run-unit-test

2021-05-20 10:37 UTC, jianzhiyao commented
/run-check_dev_2

2021-05-20 11:24 UTC, jianzhiyao commented
/run-unit-test

2021-05-20 11:36 UTC, merged