expression: mod check null iff overflow
pingcap/tidb pull request #26109
Opened 2021-07-10 16:58 UTC by hawkingrei

### What problem does this PR solve?

Problem Summary:

Similar to #25466
Some simple arithmetic function like Mod, check nulls every run, and the check is more expensive then the compute.
The bitmaps have been already merged, so the check is unnecessary, we can compute it anyway while there is no zero , and we don't care the result.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed and How it Works:
Avoid some branch in mod

I've done a trivial benchmark:
before

after
### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

-

2021-07-10 17:00 UTC, hawkingrei commented
/run-check_release_note

2021-07-11 11:17 UTC, hawkingrei commented
@wshwsh12 @mmyj PTAL

2021-07-11 11:21 UTC, leiysky approved these changes
LGTM

2021-07-11 14:17 UTC, mmyj approved these changes
lgtm

2021-07-11 14:20 UTC, mmyj commented
/reset lgtm

2021-07-11 14:22 UTC, mmyj requested changes
reset lgtm

2021-07-11 14:39 UTC, mmyj approved these changes
lgtm

2021-07-11 14:57 UTC, mmyj commented
@leiysky My mistake reset you lgtm, please take a look again.

2021-07-11 15:08 UTC, mmyj commented
@hawkingrei Please update the PR description, It's better to describe what expression had been optimized in this PR.

2021-07-12 02:18 UTC, hawkingrei commented
> @hawkingrei Please update the PR description, It's better to describe what expression had been optimized in this PR.

Updated

2021-07-12 02:25 UTC, leiysky approved these changes
LGTM

2021-07-12 02:52 UTC, wshwsh12 commented
/merge

2021-07-12 02:59 UTC, merged