util/checksum: migrate to testify
pingcap/tidb pull request #26252
Opened 2021-07-14 13:30 UTC by Ranxy

### What problem does this PR solve?

Issue Number: close #26169 

### What is changed and how it works?

What's Changed:
remove pingcap/check for utils/hack
refactor duplicate code

### Release note 

* No release note.

2021-07-14 13:37 UTC, Ranxy commented
/run-check_dev

2021-07-14 14:04 UTC, Ranxy commented
/cc @tiancaiamao @xhebox @disksing @tisonkun

2021-07-14 14:35 UTC, tisonkun requested changes
Thanks for submitting this PR @Ranxy !

May you shuffle helper functions after test functions? Always we focus on test functions first and optionally take a look at its helpers.

2021-07-14 15:12 UTC, Ranxy commented
@tisonkun Updated.

2021-07-14 16:02 UTC, xhebox reviewed
Rest LGTM

2021-07-14 16:21 UTC, xhebox commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
Maybe consider using `bytes.Buffer` with a dummy `Close`, it seems possible after my glance.

2021-07-14 16:21 UTC, xhebox commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
Maybe consider using `bytes.Buffer` with a dummy `Close`, it seems possible after my glance.

2021-07-15 02:37 UTC, tisonkun commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
Either is a new coupling. I'd prefer just decouple as "create", "open", "close" (return func), "remove" (return func) and compose in place. The problem here is that `defer` stmt accepts only one stmt or func block.

I'll try to create a patch on this PR in hours/

2021-07-15 02:38 UTC, tisonkun commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
... or make use of create tmp file.

2021-07-15 02:55 UTC, Ranxy commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
@xhebox  This is an exciting idea, and I believe it is possible to use a fake close file for this purpose.

2021-07-15 03:07 UTC, Ranxy commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
@tisonkun This sounds great, but it still requires the user to be careful about using the two return func.

2021-07-15 03:18 UTC, xhebox commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
@Ranxy It is still a problem you have called multiple `createTestFile` with same paths. Fake `close` is for `bytes.Buffer` idea, which doesn't need `close` at all.

2021-07-15 03:19 UTC, xhebox commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
> Either is a new coupling. I'd prefer just decouple...

I think it is acceptable to have a specific function for specific problems. The coupling is not so complex anyway.

2021-07-15 03:58 UTC, tisonkun commented
@Ranxy I'm creating a PR for you, please wait to make other changes.

2021-07-15 04:06 UTC, tisonkun commented
@Ranxy you can take a look at https://github.com/Ranxy/tidb/pull/1 .

2021-07-15 04:07 UTC, tisonkun reviewed
I've created a PR for you. You can take a look at https://github.com/Ranxy/tidb/pull/1 .

Basically it reduces unnecessary file operation and improve ticase comments.

2021-07-15 04:11 UTC, tisonkun commented on util/checksum/checksum_test.go
> +func createTestFileWithoutClose(t *testing.T, path string) (f *os.File, clean func()) {
@xhebox see my patch for no file op helper at all https://github.com/Ranxy/tidb/pull/1 .

2021-07-15 04:40 UTC, Ranxy commented
@tisonkun Your modifications are very effective, and I think @xhebox's proposal is also very good, and we can completely replace `File` with the following `bytes.buffer`. which do you think is better?

```go 
type fakeFile struct {
	buf *bytes.Buffer
}
func (f *fakeFile) Write(p []byte) (n int, err error) {
	return f.buf.Write(p)
}
func (f *fakeFile) Close() error {
	return nil
}
func (f *fakeFile) ReadAt(p []byte, off int64) (n int, err error) {
	w := f.buf.Bytes()
	lp := int64(len(p))
	lw := int64(len(w))
	if off > lw {
		return 0, io.EOF
	}
	if off+lp > lw {
		copy(p[:lw-off], w[off:])
		return int(lw - off), io.EOF
	}
	copy(p, w[off:off+lp])
	return len(p), nil
}
```

2021-07-15 04:46 UTC, tisonkun commented
@Ranxy you can integrate two comments and I think `Close` for byte buffer is redundant.

The parallelism refactor and  ticase comment update in the PR Ranxy#1  it still valid and should be included in the final change set IMO :P

2021-07-15 05:37 UTC, Ranxy commented
/run-check_dev_2

2021-07-15 05:45 UTC, tisonkun approved these changes
LGTM

2021-07-15 06:28 UTC, xhebox reviewed
Rest LGTM

2021-07-15 06:28 UTC, xhebox commented on util/checksum/checksum_test.go
> +	return len(p), nil
Futher simplification can be made:

```
func (f *fakeFile) ReadAt(p []byte, off int64) (n int, err error) {
	w := f.buf.Bytes()
	lp := int64(len(p))
	lw := int64(len(w))
	if off > lw {
		return 0, io.EOF
	}
	lc := copy(p, w[off:])
        if lc == lw-off {
	   return lc, io.EOF
        } else {
           return lc, nil
        }
}
```

2021-07-15 07:08 UTC, xhebox approved these changes

2021-07-15 07:08 UTC, Ranxy commented
/run-check_dev_2

2021-07-15 11:36 UTC, tiancaiamao approved these changes

2021-07-15 11:37 UTC, Ranxy commented
/run-check_dev_2

2021-07-15 12:19 UTC, Ranxy commented
@tiancaiamao  @xhebox Thanks for your review! May you help with merging this PR?

2021-07-15 12:52 UTC, tiancaiamao commented
/merge

2021-07-15 12:59 UTC, merged

2021-09-23 16:25 UTC, tisonkun commented on util/checksum/checksum_test.go
> +			assert.ErrorIs(t, err, errChecksumFail)
This line now creates unstable test

```
[2021-09-23T16:00:22.934Z] --- FAIL: TestModifyOneByte (0.00s)
[2021-09-23T16:00:22.934Z]     --- FAIL: TestModifyOneByte/encrypted (0.00s)
[2021-09-23T16:00:22.934Z]         checksum_test.go:179: 
[2021-09-23T16:00:22.934Z]             	Error Trace:	checksum_test.go:179
[2021-09-23T16:00:22.934Z]             	            				checksum_test.go:150
[2021-09-23T16:00:22.934Z]             	Error:      	Target error should be in err chain:
[2021-09-23T16:00:22.934Z]             	            	expected: "error checksum"
[2021-09-23T16:00:22.934Z]             	            	in chain: 
[2021-09-23T16:00:22.934Z]             	Test:       	TestModifyOneByte/encrypted
```