util/execdetails: remove pingcap/check for execdetails_test
pingcap/tidb pull request #26300
Opened 2021-07-16 08:58 UTC by jyz0309

### What problem does this PR solve?
Issue Number: close #26285 

Problem Summary:
util/execdetails: remove pingcap/check for execdetails_test

What's Changed:
util/execdetails: remove pingcap/check and use testify for execdetails_test

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- No Release note

2021-07-16 09:18 UTC, xhebox reviewed
Looks like tests did not make use of checkers at all? @tisonkun What do you think, would `require` and `assert` be better?

2021-07-16 10:15 UTC, tisonkun requested changes
@xhebox generally `require` acts the same as `assert` while calls `FailNow` if assertion fails.

@jyz0309 I'd suggest you make use of testify matchers to simplify the code, for example,

```go
if stats.String() != expect {
		t.Fatalf("%v != %v", stats.String(), expect)
	}
```

can be 

```go
require.Equal(t, expect, stats.String())
```

2021-07-16 10:17 UTC, jyz0309 commented
> @xhebox generally `require` acts the same as `assert` while calls `FailNow` if assertion fails.
> 
> @jyz0309 I'd suggest you make use of testify matchers to simplify the code, for example,
> 
> ```go
> if stats.String() != expect {
> 		t.Fatalf("%v != %v", stats.String(), expect)
> 	}
> ```
> 
> can be
> 
> ```go
> require.Equal(t, expect, stats.String())
> ```

OK，Will finish it this weekend

2021-07-17 09:37 UTC, xhebox reviewed
`TestFormatDurationForExplain`, `TestRootRuntimeStats`, `TestRuntimeStatsWithCommit`, `TestCopRuntimeStatsForTiFlash` may make use of `assert/require`, too.

2021-07-17 09:37 UTC, xhebox commented on util/execdetails/execdetails_test.go
> +	assert.NotNil(t, copStats)
`require.NotNil` will fail faster and better.

2021-07-19 05:41 UTC, jyz0309 commented
cc @tisonkun

2021-07-19 06:23 UTC, tisonkun approved these changes
LGTM

2021-07-19 06:29 UTC, xhebox approved these changes

2021-07-19 07:06 UTC, tisonkun commented
/cc @mmyj @tiancaiamao 

May you help on reviewing this PR? Thanks!

2021-07-20 13:22 UTC, tiancaiamao approved these changes

2021-07-20 13:22 UTC, tiancaiamao commented
/merge

2021-07-21 04:11 UTC, tisonkun commented
/cc @zimulala @lysu

2021-07-21 05:45 UTC, lysu approved these changes

2021-07-21 05:45 UTC, lysu commented
/merge

2021-07-21 07:01 UTC, merged