migrate test-infra to testify for `server/conn_test.go`
pingcap/tidb pull request #27407
Opened 2021-08-20 02:42 UTC by yedamao

### What problem does this PR solve?

Issue Number: close #27343  

### Release note 

```release-note
None.
```

2021-08-20 02:43 UTC, yedamao commented
/cc @tisonkun

2021-08-20 02:47 UTC, yedamao commented
/run-check_title

2021-08-20 02:57 UTC, tisonkun requested changes
The direction of this pr is in a wrong direction. Please take a look at https://github.com/pingcap/tidb/pull/27377 as a demo how to migrate suite.

After this patch, there is still "pingcap/check" dependency and leaktest...

2021-08-20 02:59 UTC, tisonkun commented
This suite can fit the pattern `testkit.CreateMockStore`, just use it.

2021-08-20 10:46 UTC, yedamao commented
> After this patch, there is still "pingcap/check" dependency and leaktest...

Some tests remains in conn_stmt_test.go, when the migration is complete, it will be removed.

2021-08-20 11:07 UTC, yedamao commented
> This suite can fit the pattern `testkit.CreateMockStore`, just use it.
> 
> You can extend the original function with a `MockTiKVStoreOption` parameter.

I checked the `testkit.CreateMockStore`  and #27377. 
The `testkit.CreateMockStore` just return a mockstore, but some tests also depend on `domain.Domain`.

2021-08-20 13:01 UTC, tisonkun commented
@yedamao be aware that you are a TiDB developer. You can always change the function on demand if reasonable.

2021-08-20 13:41 UTC, yedamao commented on server/conn_test.go
> +
@tisonkun How about move this connTestHelper to testkit pkg as a common test helper.

2021-08-20 14:53 UTC, yedamao commented
@tisonkun Please take a look at 9487285

2021-08-20 15:21 UTC, tisonkun commented
> @tisonkun Please take a look at [9487285](https://github.com/pingcap/tidb/commit/94872850f824a1f01fae92f110659529f58e4abf)

It looks in a right direction.

2021-08-24 02:47 UTC, yedamao commented
/run-check_dev_2

2021-08-24 13:59 UTC, yedamao commented
/run-check_dev_2

2021-08-30 09:50 UTC, tiancaiamao approved these changes

2021-08-31 03:47 UTC, xhebox approved these changes

2021-08-31 03:47 UTC, xhebox commented
/merge

2021-08-31 04:09 UTC, tisonkun commented
/run-check_dev_2

emm...

[2021-08-31T03:56:07.849Z] The following test cases take too long to finish:
[2021-08-31T03:56:07.849Z] PASS: tidb_test.go:878: tidbTestSerialSuite.TestTLSAuto	5.054s

2021-08-31 05:24 UTC, merged