sessionctx/binloginfo: migrate test-infra to testify for sessionctx/binloginfo (#27279)
pingcap/tidb pull request #27572
Opened 2021-08-25 06:48 UTC by Defined2014

### What problem does this PR solve?

Issue Number: close #27279 

### Release note 

```release-note
None
```

2021-08-25 07:37 UTC, Defined2014 commented
/run-build

2021-08-25 07:49 UTC, Defined2014 commented
/cc @tisonkun PTAL
For easy to implement, I used stretchr/testify/suite to instead of orignal suite. Also changed testkit/testkit.go and tools/check/check_testSuite.sh. The reason is below:
* testkit.go: follow the util/testkit/testkit.go logical, create session when call Exec. Because session.BootstrapSession() func will close the session pool.
* check_testSuite.sh: I still use suite, but didn't call "Suite|SerialSuites" func. I take a work around to fix it by change the shell script. I think you can rewrite the shell script when migrate finish.

2021-08-25 09:40 UTC, Defined2014 commented
/run-all-tests

2021-08-25 09:53 UTC, Defined2014 commented
/cc @morgo @bb7133

2021-08-25 10:46 UTC, tisonkun requested changes
as mention in the tracking issue:

> Avoid using suite of testify as discussed https://github.com/pingcap/tidb/pull/26082#issuecomment-877230972

You can refer to other test case where `testkit.CreateMockStore` in use. And try to batch setup / teardown logic only if necessary.

2021-08-25 12:13 UTC, tisonkun commented on sessionctx/binloginfo/binloginfo_test.go
> +	require.NotNil(t, err)
`require.Error(t, err)` ditto others

2021-08-25 12:14 UTC, tisonkun commented on sessionctx/binloginfo/binloginfo_test.go
> +	require.Nil(t, err)
`require.NoError(t, err)` ditto others.

2021-08-25 12:15 UTC, tisonkun commented on testkit/testkit.go
> -func newSession(t *testing.T, store kv.Storage) session.Session {
why make this change?

2021-08-30 02:44 UTC, Defined2014 commented
/run-check_dev_2

2021-08-30 04:16 UTC, Defined2014 commented
/run-check_dev_2

2021-08-30 05:52 UTC, Defined2014 commented
/run-check_dev_2

2021-08-30 09:07 UTC, Defined2014 commented
/cc @zimulala

2021-08-30 09:14 UTC, zimulala approved these changes
LGTM

2021-08-30 09:15 UTC, zimulala commented
/merge

2021-08-30 09:23 UTC, Defined2014 commented
/run-check_dev_2

2021-08-30 09:30 UTC, Defined2014 commented
/run-check_dev_2

2021-08-30 09:44 UTC, merged