Add metrics for pd api call time
pingcap/tidb pull request #30062
Opened 2021-11-23 10:24 UTC by jyz0309

Signed-off-by: jyz0309 <45495947@qq.com>

### What problem does this PR solve?

Issue Number: close #29821 

Problem Summary:

### What is changed and how it works?
Add Metrics to Monitor PD API call exection time 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Add Metrics to Monitor PD API call exection time 
```

2021-11-23 14:26 UTC, jyz0309 commented
/cc @morgo

2021-11-28 23:58 UTC, morgo commented
LGTM (non binding; I am not much of a prometheus user.)

2021-11-29 02:33 UTC, jyz0309 commented
/cc @reviewer

2021-11-29 02:33 UTC, jyz0309 commented
/cc @xhebox @AilinKid

2021-11-29 02:40 UTC, xhebox requested changes
LGTM, but this is not what we want for the placement issue. There are more than one occurences of PD API.

https://github.com/pingcap/tidb/blob/d3a4187f7e99a0c156912b6831686e89fc8b6a85/domain/infosync/info.go#L333-L380

FYI, for placement rules, we primaryly want to monitor this function, instead.

2021-11-29 02:41 UTC, AilinKid approved these changes
LGTM

2021-11-30 01:56 UTC, jyz0309 commented on metrics/server.go
> +		}, []string{LblType})
I add a `enum{common, placement}` label for this metric. Plz correct me if you have a better idea. @xhebox

2021-11-30 04:39 UTC, xhebox commented on store/helper/helper.go
> +	metrics.PDApiExecutionHistogram.WithLabelValues("common").Observe(time.Since(start).Seconds())
You did not count the errored requests in. What about moving observe before `err ...` condition branch.

2021-12-01 07:21 UTC, xhebox approved these changes

2021-12-01 07:22 UTC, xhebox commented
/merge

2021-12-01 10:49 UTC, merged