*: replace compareDatum by compare
pingcap/tidb pull request #30456
Opened 2021-12-07 02:45 UTC by wjhuang2016

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Related to #29867.

### What is changed and how it works?

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

2021-12-07 03:29 UTC, qw4990 approved these changes

2021-12-07 09:03 UTC, XuHuaiyu requested changes

2021-12-07 09:03 UTC, XuHuaiyu commented on executor/builder.go
> +	keyCtors := make([]collate.Collator, 0, len(v.InnerJoinKeys))
keyCollators

2021-12-07 09:03 UTC, XuHuaiyu commented on executor/builder.go
> +	hashCtors := make([]collate.Collator, 0, len(v.InnerHashKeys))
hashCollators

2021-12-08 04:15 UTC, XuHuaiyu approved these changes
LGTM

2021-12-08 04:16 UTC, XuHuaiyu commented
/merge

2021-12-08 04:20 UTC, XuHuaiyu approved these changes

2021-12-08 06:08 UTC, qw4990 approved these changes

2021-12-08 09:32 UTC, wjhuang2016 commented
/merge

2021-12-08 09:35 UTC, merged