planner: fix wrong collation when rewrite in condition
pingcap/tidb pull request #30492
Opened 2021-12-07 12:08 UTC by wjhuang2016

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #30486

Problem Summary:
When rewriting IN to EQ, we need to set the collation correctly.

### What is changed and how it works?

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

2021-12-07 12:54 UTC, bb7133 approved these changes
LGTM

2021-12-08 06:45 UTC, xiongjiwei commented
/run-check_dev_2

2021-12-08 06:52 UTC, xhebox approved these changes

2021-12-08 07:07 UTC, xhebox requested changes
Then failed tests look stable, @wjhuang2016 :

```
prepare stmt from 'select col1 from t where (col1, col2) in ((?, 1));';, [], error stack [expression:1241]Operand should contain 2 column(s)
```

2021-12-08 13:09 UTC, bb7133 commented on planner/core/expression_rewriter.go
> +			if er.ctxStack[i].GetType().EvalType() == types.ETString && l == 1 {
Well, I got confused by the condition `l == 1`, could you explain it and add some comments here?

2021-12-08 13:20 UTC, wjhuang2016 commented on expression/builtin_cast.go
> +	bf.args[0] = HandleBinaryLiteral(ctx, args[0], &ExprCollation{Charset: c.tp.Charset, Collation: c.tp.Collate}, c.funcName)
Wait for another PR to fix it.

2021-12-08 13:21 UTC, wjhuang2016 commented on expression/builtin_convert_charset.go
> +		ast.NE, ast.NullEQ, ast.Strcmp, ast.If, ast.Ifnull, ast.Like, ast.In, ast.DateFormat, ast.TimeFormat, ast.Cast:
Wait for another PR to fix it.

2021-12-09 01:59 UTC, bb7133 commented on expression/builtin_cast.go
> +	bf.args[0] = HandleBinaryLiteral(ctx, args[0], &ExprCollation{Charset: c.tp.Charset, Collation: c.tp.Collate}, c.funcName)
Which PR is it?

2021-12-21 10:07 UTC, xiongjiwei approved these changes

2021-12-21 12:30 UTC, xhebox approved these changes

2021-12-21 12:31 UTC, xhebox commented
/merge

2021-12-21 12:47 UTC, merged