ddl: migrate test-infra to testify for ddl/column_change_test.go
pingcap/tidb pull request #30834
Opened 2021-12-17 05:54 UTC by GOODBOY008

### What problem does this PR solve?

Issue Number: close #28630

Problem Summary:

### What is changed and how it works?

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

2021-12-17 05:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/tidb?pullRequest=30834) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/tidb?pullRequest=30834) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/tidb?pullRequest=30834) it.</sub>

2021-12-17 06:03 UTC, GOODBOY008 commented
/cc @tisonkun

2021-12-18 01:32 UTC, tisonkun requested changes
@GOODBOY008 please take a look at existing migration example such as under `expression` package. This patch is invalid and shows that you don't know how go testing works. Also, CI tasks failed.

You should remove "pingcap/check" dependency and migrate its `Suite` and thus `SetUpSuite`/`TearDownSuite` logics.

2021-12-18 03:03 UTC, hawkingrei commented on ddl/column_change_test.go
> +	require.Nil(t, err)
require.NoError(t, err)

2021-12-18 03:03 UTC, hawkingrei commented on ddl/column_change_test.go
> +	require.Nil(t, err)
Ditto

2022-05-17 13:48 UTC, closed without merging