store: avoid setting ratelimit action in tracker when disabled
pingcap/tidb pull request #31110
Opened 2021-12-29 04:54 UTC by Yisaer

Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

When `tidb_enable_rate_limit_action` is disabled, ratelimit action will still be set in memory tracker which would consume unnecessary performance

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

avoid setting ratelimit action in tracker when disabled

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

2022-01-04 08:19 UTC, ichn-hu requested changes

2022-01-04 08:19 UTC, ichn-hu commented on executor/aggregate.go
> +	return "aggregation_spill_disk_action"
I would suggest using enum instead of magic strings here

2022-01-04 08:19 UTC, ichn-hu commented on session/session_test.go
> +		if action.GetType() == "rate_limit_action" {
avoid using magic string

2022-01-11 06:59 UTC, wshwsh12 commented on util/memory/action.go
> +	GetType() string
Can we use GetPriority() to check whether the acion is rateLimitAction?

2022-03-25 09:01 UTC, wshwsh12 approved these changes
LGTM

2022-03-25 09:12 UTC, hawkingrei approved these changes

2022-03-25 09:24 UTC, Yisaer commented
/merge

2022-03-25 09:39 UTC, JmPotato commented
LGTM

2022-03-25 09:40 UTC, JmPotato approved these changes

2022-03-25 09:40 UTC, Yisaer commented
/merge

2022-03-25 10:11 UTC, Yisaer commented
/run-unit-test

2022-03-25 10:11 UTC, Yisaer commented
/run-mysql-test

2022-03-25 10:51 UTC, hawkingrei commented
/merge

2022-03-25 11:00 UTC, hawkingrei approved these changes

2022-03-25 11:00 UTC, hawkingrei commented
/merge

2022-03-25 11:28 UTC, Yisaer commented
/run-unit-test

2022-03-26 03:27 UTC, Yisaer commented
/run-unit-test

2022-03-27 12:23 UTC, hawkingrei commented
/merge

2022-03-28 02:18 UTC, Yisaer commented
/run-unit-test

2022-03-28 04:11 UTC, Yisaer commented
/run-unit-test

2022-03-28 04:11 UTC, Yisaer commented
/run-mysql-test

2022-03-28 06:51 UTC, Yisaer commented
/run-unit-test

2022-03-28 08:13 UTC, Yisaer commented
/run-unit-test

2022-03-28 12:13 UTC, Yisaer commented
/run-unit-test

2022-03-28 12:27 UTC, Yisaer commented
/merge

2022-03-29 02:59 UTC, ichn-hu approved these changes

2022-03-29 03:02 UTC, merged