executor: migrate test-infra to testify for parallel_apply_test.go
pingcap/tidb pull request #32686
Opened 2022-03-01 05:50 UTC by feitian124

### What problem does this PR solve?

Issue Number: close #28599 

### Release note

```release-note
None
```

2022-03-01 06:08 UTC, hawkingrei approved these changes

2022-03-01 06:08 UTC, hawkingrei commented
/cc @tisonkun

2022-03-01 06:23 UTC, xiongjiwei approved these changes

2022-03-01 06:23 UTC, xiongjiwei commented
/merge

2022-03-01 06:26 UTC, tisonkun approved these changes

2022-03-01 06:28 UTC, tisonkun requested changes
`NewTestKitWithInit` is somehow too much to encapsulate and I intend to avoid it but with one more line `tk.MustExec("use test")`

Most developers aren't aware difference between `NewTestKitWithInit` and `NewTestKit` but choose either randomly. I think make it explicit should help.

2022-03-01 06:28 UTC, tisonkun commented on executor/parallel_apply_test.go
> +	tk := testkit.NewTestKitWithInit(t, store)
```suggestion
	tk := testkit.NewTestKitWithInit(t, store)
	tk.MustExec("use test")
```

ditto others

2022-03-01 06:28 UTC, tisonkun commented on testkit/testkit.go
> +}
Please remove this method.

2022-03-01 06:28 UTC, tisonkun commented
/merge-cancel

2022-03-01 09:49 UTC, tisonkun commented on executor/parallel_apply_test.go
> +	tk := testkit.NewTestKitWithInit(t, store)
I'm going to push a patch now.

2022-03-01 09:53 UTC, tisonkun approved these changes

2022-03-01 09:53 UTC, tisonkun commented
/cc @hawkingrei @xiongjiwei

2022-03-02 02:01 UTC, hawkingrei approved these changes

2022-03-02 02:02 UTC, tisonkun commented
/merge

2022-03-02 02:43 UTC, feitian124 commented
/run-unit-test

2022-03-02 03:07 UTC, merged