*: remove useless gomod
pingcap/tidb pull request #36516
Opened 2022-07-25 07:40 UTC by hawkingrei

Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

2022-07-25 16:38 UTC, ngaut approved these changes

2022-07-26 03:41 UTC, xhebox approved these changes

2022-07-26 03:43 UTC, xhebox requested changes
@hawkingrei  Obviously, CI failed to build tools after removing `go.mod`. Maybe `GOTOOLDIR=xxx go install` is a better alternative.

2022-08-12 16:30 UTC, hawkingrei commented
> @hawkingrei Obviously, CI failed to build tools after removing `go.mod`. Maybe `GOTOOLDIR=xxx go install xxx@v1.x.x` is a better alternative.

OK, Now We have changed into this method. We can merge it.

2022-08-13 18:46 UTC, xhebox approved these changes

2022-08-14 01:50 UTC, tisonkun approved these changes

2022-08-14 01:50 UTC, tisonkun commented
/merge

2022-08-14 02:00 UTC, merged