ddl, metrics: remove cleanExpirePath
pingcap/tidb pull request #36863
Opened 2022-08-03 12:27 UTC by wjhuang2016

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### What is changed and how it works?

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

2022-08-03 13:15 UTC, lcwangchao approved these changes

2022-08-03 23:35 UTC, ngaut approved these changes

2022-08-03 23:36 UTC, ngaut commented
Could you post a link about the the bug reference of etcd?

2022-08-04 00:21 UTC, hawkingrei commented
/hold

2022-08-04 01:53 UTC, zimulala commented on ddl/ddl.go
> -	go d.schemaSyncer.StartCleanWork()
We need to remove `metrics.DDLCounter.WithLabelValues(metrics.StartCleanWork).Inc()` in line667.

2022-08-04 01:53 UTC, zimulala commented on ddl/util/syncer.go
> +		ownerChecker:      oc,
Could we remove `ownerChecker` too?

2022-08-04 01:56 UTC, zimulala requested changes

2022-08-04 01:56 UTC, zimulala commented on metrics/ddl.go
> -	OwnerHandleSyncerHistogram  = prometheus.NewHistogramVec(
Please remove `StartCleanWork` in [line105](https://github.com/pingcap/tidb/pull/36863/files#diff-e880516abc91d29e0ea2a8619091e50fd31338e2a9fae2d4da360662b8d5cbe1L105)

2022-08-04 02:02 UTC, zimulala commented
> Could you post a link about the the bug reference of etcd?

[The key is not deleted when the bound lease expires](https://github.com/etcd-io/etcd/issues/10686)

2022-08-04 03:17 UTC, hawkingrei commented
/unhold

2022-08-04 03:57 UTC, zimulala approved these changes
LGTM

2022-08-04 04:03 UTC, hawkingrei approved these changes

2022-08-04 05:09 UTC, wjhuang2016 commented
/merge

2022-08-04 05:34 UTC, merged