*: make auto-analyze's tidb_index_serial_scan_concurrency configurable
pingcap/tidb pull request #50412
Opened 2024-01-15 04:02 UTC by hawkingrei

### What problem does this PR solve?

Issue Number: close #50362

Problem Summary:

### What changed and how does it work?

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

2024-01-15 04:20 UTC, hawkingrei commented
/retest

2024-01-15 06:05 UTC, hi-rustin requested changes
Please add some explanation in the body of your PR. Otherwise, in the future when someone opens this PR, they will have no idea what is going on and why need to make this change.

Thanks!

2024-01-18 05:16 UTC, hawkingrei commented
> Please add some explanation in the body of your PR. Otherwise, in the future when someone opens this PR, they will have no idea what is going on and why need to make this change.
> 
> Thanks!

Updated

2024-01-18 05:17 UTC, hi-rustin approved these changes

2024-01-18 09:13 UTC, hawkingrei commented
/cherrypick release-7.6

2024-01-18 09:13 UTC, merged