executor: check schema when build table reader executor
pingcap/tidb pull request #50425
Opened 2024-01-15 08:10 UTC by yibin87

### What problem does this PR solve?

Issue Number: ref #50358

Problem Summary:
Described in #50358
### What changed and how does it work?
Quick fix for the issue in executor. Had tried to fix it in planner phase, but failed: https://github.com/pingcap/tidb/pull/50410

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Try to run cross join queries with high concurrency, and check no empty result sets are found
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

2024-01-15 08:12 UTC, yibin87 commented
/cc @windtalker @elsa0520

2024-01-16 05:52 UTC, elsa0520 commented on pkg/executor/builder.go
> +	// https://github.com/pingcap/tidb/issues/50358
Please add the test ~

2024-01-16 06:02 UTC, yibin87 commented on pkg/executor/builder.go
> +	// https://github.com/pingcap/tidb/issues/50358
ok

2024-01-17 01:49 UTC, hawkingrei commented
/ok-to-test

2024-01-17 10:34 UTC, elsa0520 requested changes
This is not a good changed for this issue.
We should keep the tablereader schema correctly in planner.

2024-01-18 01:33 UTC, yibin87 commented
> This is not a good changed for this issue. We should keep the tablereader schema correctly in planner.

Yeah, that's the reason why this is not a PR that closes the issue but ref it. This PR aims to pass some regression tests. I tried  to fix the issue in planner phase in #50410 and recorded some other tries, while introducing many test failures. Thus I submit this PR to pass regression tests.

2024-01-18 04:17 UTC, elsa0520 commented
> > This is not a good changed for this issue. We should keep the tablereader schema correctly in planner.
> 
> Yeah, that's the reason why this is not a PR that closes the issue but ref it. This PR aims to pass some regression tests. I tried to fix the issue in planner phase in #50410 and recorded some other tries, while introducing many test failures. Thus I submit this PR to pass regression tests.

OK, for quickly pass the test I can approve this PR. But we should directly fix this issue by following planner PR later.

2024-01-18 04:18 UTC, elsa0520 approved these changes
Later to fix it correctly.

2024-01-18 05:43 UTC, windtalker approved these changes
LGTM

2024-01-18 07:53 UTC, yibin87 commented
/test mysql-test

2024-01-18 09:55 UTC, merged