planner: Change the rewrite rule of row expression
pingcap/tidb pull request #53928
Opened 2024-06-11 08:11 UTC by elsa0520

### What problem does this PR solve?

(x,y,z) op (a,b,c)
rewritten
(x op a) or (x = a and y op b) or (x = a and y = b and z op c)

The new rewriting method allows buildrange to handle range construction problems more conveniently.

Issue Number: close #41598

Problem Summary:

### What changed and how does it work?

The old expression rewrite is rewritten row expression to if(x!=a, x> a, if(xxxx)). The range builder could not easy build and merge this kind of expr range.

The new expression rewritten to (x op a) or (x = a and y op b) or (x = a and y = b and z op c) . It will be rewritten as a DNF which is more conveniently for Range builder.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The row expression will be rewritten into DNF. This form is more conducive to more precise range builder of the index, thereby reducing key reading.
```

2024-06-11 08:12 UTC, elsa0520 commented
Testing, not ready to merge

2024-06-12 03:23 UTC, fixdb reviewed
Are you going to add test cases?

2024-06-12 08:18 UTC, elsa0520 commented
> Are you going to add test cases?

Yes, I haven't finish the test.

2024-06-14 06:19 UTC, hawkingrei commented on pkg/planner/core/casetest/index/index_test.go
> +func TestRowFunctionMatchTheIndexRangeScan(t *testing.T) {
Please run the ```make bazel_prepare``` and sync with master.

2024-06-14 06:40 UTC, elsa0520 commented on pkg/planner/core/casetest/index/index_test.go
> +func TestRowFunctionMatchTheIndexRangeScan(t *testing.T) {
Done

2024-06-14 16:12 UTC, ghazalfamilyusa requested changes

2024-06-14 16:12 UTC, ghazalfamilyusa commented on pkg/planner/core/casetest/index/testdata/integration_suite_in.json
> +    "name": "TestRowFunctionMatchTheIndexRangeScan",
Looks good overall. Could you add tests: (1) between like (k1,k2) between ...  (2) mix of upper and lower bounds (3) row function and ranges on individual columns.

2024-06-17 13:30 UTC, time-and-fate reviewed
Others LGTM.

2024-06-17 17:37 UTC, ghazalfamilyusa approved these changes

2024-06-18 04:14 UTC, elsa0520 commented on pkg/planner/core/expression_rewriter.go
> +			// l[0] = r[0] and l[1] = r[1] and ... and l[i-1] = r[i-1]
Changed

2024-06-18 04:18 UTC, hawkingrei commented
/ok-to-test

2024-06-18 04:21 UTC, time-and-fate approved these changes

2024-06-18 05:28 UTC, elsa0520 commented
/test unit-test

2024-06-20 07:42 UTC, elsa0520 commented
/test unit-test

2024-06-20 10:01 UTC, AilinKid approved these changes

2024-06-20 10:13 UTC, hawkingrei approved these changes

2024-06-20 11:02 UTC, merged