expression: Fix optimizer panic in evaluate expr with null
pingcap/tidb pull request #57403
Opened 2024-11-15 05:13 UTC by windtalker

### What problem does this PR solve?

Issue Number: close #55886

Problem Summary:

### What changed and how does it work?
1. Both `evaluateExprWithNull` and `evaluateExprWithNullInNullRejectCheck` use `NewFunction` instead of `NewFunctionInternal` to create a scalar function
2. let `EvaluateExprWithNull` return error if some error happens inside `EvaluateExprWithNull`
2. The caller of `EvaluateExprWithNull` need to decide how to handle this error, currently, all the callers of `EvaluateExprWithNull` are optimizer, and will ignore the error
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

2024-11-15 18:01 UTC, ghazalfamilyusa requested changes
Looks good overall. My comments is about adding the test to 
 the original pkg/planner/core/casetest/rule/testdata/outer2inner_in.json test and testing the expression evaluation in the non-optimizer path.

2024-11-18 02:03 UTC, windtalker commented on pkg/expression/integration_test/integration_test.go
> +func TestIssue55886(t *testing.T) {
Done

2024-11-18 02:04 UTC, windtalker commented
> Looks good overall. My comments is about adding the test to the original pkg/planner/core/casetest/rule/testdata/outer2inner_in.json test and testing the expression evaluation in the non-optimizer path.

`EvaluateExprWithNull` is now only used by optimizer, but I add a ut to test that `EvaluateExprWithNull` do return error if there is some error happens inside.

2024-11-19 00:46 UTC, ghazalfamilyusa approved these changes

2024-11-19 03:01 UTC, XuHuaiyu approved these changes

2024-11-19 09:16 UTC, AilinKid approved these changes

2024-11-19 11:03 UTC, merged